In [41]:
import pandas as pd
import numpy as np
import matplotlib as plt
from datetime import datetime, timedelta


In [42]:
# load training data set from https://www.kaggle.com/competitions/house-prices-advanced-regression-techniques/

KC = pd.read_csv("data/final_data_set_schl_crm.csv", parse_dates = ['SOLD DATE'])
KC

SALE TYPE  SOLD DATE              PROPERTY TYPE  \
0       PAST SALE 1991-03-14  Single Family Residential   
1     MLS Listing        NaT                Condo/Co-op   
2       PAST SALE 2010-02-19  Single Family Residential   
3       PAST SALE        NaT  Single Family Residential   
4       PAST SALE        NaT  Single Family Residential   
...           ...        ...                        ...   
7061  MLS Listing        NaT  Single Family Residential   
7062  MLS Listing        NaT  Single Family Residential   
7063  MLS Listing        NaT  Single Family Residential   
7064  MLS Listing        NaT  Single Family Residential   
7065    PAST SALE 2010-08-27                  Townhouse   

                        ADDRESS       CITY STATE OR PROVINCE  zipcode  \
0               4442 S 351st St     Auburn                WA    98001   
1     28700 34th Ave S Unit M-3     Auburn                WA    98001   
2               3414 S 283rd Ln     Auburn                WA    98001   
3               29382 58th Ct S     Auburn                WA    98001   
4               29391 58th Ct S     Auburn                WA    98001   
...                         ...        ...               ...      ...   
7061            301 NW 100th St    Seattle                WA    98177   
7062            55 Spring Dr NW  Shoreline                WA    98177   
7063           1229 NW 122nd St    Seattle                WA    98177   
7064          1295 NW Elford Dr    Seattle                WA    98177   
7065       10130 C Holman Rd NW    Seattle                WA    98177   

           PRICE  BEDS  BATHS  ...                            SOURCE  \
0       549950.0   3.0    2.0  ...  NWMLS as Distributed by MLS Grid   
1       455000.0   2.0    2.0  ...  NWMLS as Distributed by MLS Grid   
2       599000.0   3.0    2.5  ...  NWMLS as Distributed by MLS Grid   
3       819950.0   4.0    2.5  ...  NWMLS as Distributed by MLS Grid   
4       860675.0   5.0    3.5  ...  NWMLS as Distributed by MLS Grid   
...          ...   ...    ...  ...                               ...   
7061   1398000.0   4.0    3.5  ...  NWMLS as Distributed by MLS Grid   
7062   4500000.0   3.0    3.5  ...  NWMLS as Distributed by MLS Grid   
7063   2399000.0   4.0    3.5  ...  NWMLS as Distributed by MLS Grid   
7064  10950000.0   4.0    5.0  ...  NWMLS as Distributed by MLS Grid   
7065    575000.0   3.0    1.5  ...  NWMLS as Distributed by MLS Grid   

           MLS#  FAVORITE  INTERESTED   LATITUDE   LONGITUDE  num_school  \
0       2221171         N           Y  47.287207 -122.278138          11   
1       2195712         N           Y  47.344974 -122.289366          11   
2       2227709         N           Y  47.347788 -122.290089          11   
3       2203868         N           Y  47.326852 -122.261718          11   
4       2189261         N           Y  47.326852 -122.261718          11   
...         ...       ...         ...        ...         ...         ...   
7061  2186750.0         N           Y  47.701517 -122.360742           4   
7062  2170295.0         N           Y  47.739328 -122.374897           4   
7063  2170063.0         N           Y  47.718042 -122.373280           4   
7064  2152029.0         N           Y  47.730286 -122.371717           4   
7065  2192480.0         N           Y  47.702735 -122.359131           4   

     school_rating_mean Bayes_RatingSchool crime_percentage  
0              1.454545           1.996248            28.96  
1              1.454545           1.996248            28.96  
2              1.454545           1.996248            28.96  
3              1.454545           1.996248            28.96  
4              1.454545           1.996248            28.96  
...                 ...                ...              ...  
7061           3.750000           3.617964            24.76  
7062           3.750000           3.617964            24.76  
7063           3.750000           3.617964            24.76  
7064           3.750000 

In [191]:
# look at the columns
KC.columns

Index(['SALE TYPE', 'SOLD DATE', 'PROPERTY TYPE', 'ADDRESS', 'CITY',
       'STATE OR PROVINCE', 'zipcode', 'PRICE', 'BEDS', 'BATHS', 'LOCATION',
       'SQUARE FEET', 'LOT SIZE', 'YEAR BUILT', 'DAYS ON MARKET',
       '$/SQUARE FEET', 'HOA/MONTH', 'STATUS', 'NEXT OPEN HOUSE START TIME',
       'NEXT OPEN HOUSE END TIME',
       'URL (SEE https://www.redfin.com/buy-a-home/comparative-market-analysis FOR INFO ON PRICING)',
       'SOURCE', 'MLS#', 'FAVORITE', 'INTERESTED', 'LATITUDE', 'LONGITUDE',
       'num_school', 'school_rating_mean', 'Bayes_RatingSchool',
       'crime_percentage'],
      dtype='object')

In [192]:
# look at the columns information
KC.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7066 entries, 0 to 7065
Data columns (total 31 columns):
 #   Column                                                                                       Non-Null Count  Dtype  
---  ------                                                                                       --------------  -----  
 0   SALE TYPE                                                                                    7066 non-null   object 
 1   SOLD DATE                                                                                    1792 non-null   object 
 2   PROPERTY TYPE                                                                                7066 non-null   object 
 3   ADDRESS                                                                                      7054 non-null   object 
 4   CITY                                                                                         7064 non-null   object 
 5   STATE OR PROVINCE                 

### Unique values for the categorical variables

In [193]:
# Identify categorical columns (either object or category dtype)
categorical_columns = KC.select_dtypes(include=['object', 'category']).columns

# Iterate through categorical columns and print unique values
for col in categorical_columns:
    unique_values = KC[col].unique()
    print(f"Unique values in '{col}': {unique_values}")

Unique values in 'SALE TYPE': ['PAST SALE' 'MLS Listing' 'New Construction Plan' 'New Construction Home'
 'For-Sale-by-Owner Listing']
Unique values in 'SOLD DATE': ['March-14-1991' nan 'February-19-2010' ... 'November-9-1983'
 'August-8-2008' 'October-1-2012']
Unique values in 'PROPERTY TYPE': ['Single Family Residential' 'Condo/Co-op' 'Parking' 'Vacant Land'
 'Mobile/Manufactured Home' 'Multi-Family (2-4 Unit)' 'Townhouse'
 'Multi-Family (5+ Unit)' 'Ranch' 'Other' 'Moorage' 'Unknown']
Unique values in 'ADDRESS': ['4442 S 351st St' '28700 34th Ave S Unit M-3' '3414 S 283rd Ln' ...
 '1229 NW 122nd St' '1295 NW Elford Dr' '10130 C Holman Rd NW']
Unique values in 'CITY': ['Auburn' 'Federal Way' 'Algona' 'Bellevue' 'Clyde Hill' 'Hunts Point'
 'Yarrow Point' 'Newport Hills' 'Maple Valley' 'Black Diamond' 'Bothell'
 'Carnation' 'Duvall' 'Enumclaw' 'Fall City' 'Issaquah' 'Kenmore'
 'Sammamish' 'Kent' 'Kirkland' 'Redmond' 'Medina' 'Mercer Island'
 'Covington' 'Renton' nan 'North Bend' 'Woodin

# Describr features
|column | description |notes|
|----------|----------|-----|
| SALE TYPE|'PAST SALE' 'MLS Listing' 'New Construction Plan' 'New Construction Home' 'For-Sale-by-Owner Listing'|look at the distribution and decide on dropping|
|SOLD DATE |date the property was previously sold ? the dates are 1991, 2007, ..  | drop|
| PROPERTY TYPE | 'Single Family Residential' 'Condo/Co-op' 'Parking' 'VacantLand','Mobile/ManufacturedHome''MultiFamily(2 Unit)' 'Townhouse' 'Multi-Family (5+ Unit)' 'Ranch' 'Other' 'Moorage' 'Unknown'| price for these property type will be significantly different. Have different model for each property type? or drop the ones we are not interested in like lands |
|ADDRESS|address of the property| drop|
|CITY|lots of different unique cities|drop?maybe?look at the correlation with other|
|STATE OR PROVINCE|'WA'|drop|
|zipcode|70 unique values|keep|
|PRICE|price of the property - output variable||
|BEDS| number of bed rooms||
|BATHS| number of bath rooms||
|'LOCATION'|lots of different locations|drop? may be, look at the correlation with other|
|SQUARE FEET|look at the correlation|
|LOT SIZE||look at the correlation|
|YEAR BUILT|year the property was built|can get a new feature as age = 2024-year_built|
|DAYS ON MARKET|probably price may not depend on this|see if there is any correlation|
|$/SQUARE FEET||look at the correlation and decide drop|
|HOA/MONTH|is a float type variable, HOA = HomeOwner Association|drop|
|STATUS|status of the listing: 'Pending' 'Active'|drop|
|NEXT OPEN HOUSE START TIME||drop|
|NEXT OPEN HOUSE END TIME||drop|
|URL (SEE https://www.redfin.com/buy-a-home/comparative-market-analysis FOR INFO ON PRICING)|url of the listing|drop|
|SOURCE|'NWMLS as Distributed by MLS Grid' 'Zillow' 'FSBO.com' 'RMLS''Fizber.com' 'PACMLS' 'SPOKANEMLS as Distributed by MLS Grid'|drop|
|MLS|some kind of listing ID of some sort|drop|
|FAVORITE|whether listed as favourite by the user|drop|
|INTERESTED|'Y' 'N'|drop|
|LATITUDE||drop|
|LONGITUDE||drop|
|school_rating|raings of schools for each zip code|ratings out of 5|
|crime_percentage| crime rate per thousand people |percentage? |


## HOA/month  = HomeOwner Association price per month 

An HOA is a legal entity that manages a shared housing complex, whether it’s a condo building, a row of townhouses or a suburban housing development with shared space. Almost all townhomes fall under the jurisdiction of an HOA and every condo is part of an HOA. However, almost all single-family houses are “fee simple,” meaning that the buyer owns the home and all of the land associated with a purchase, and has no obligation to an HOA.

Your HOA manages (and pays for) the common elements in your development, which can include things like a shared roof (in a condo building), landscaping, snow removal from sidewalks and parking lots, shared fencing, mailboxes and entry gates. It also includes things like paying for the development’s security, maintaining a shared swimming pool or playground and managing a shared septic system. 

### HOA/month is n/a for 3703 rows we can drop this column 

In [36]:
KC

SALE TYPE         SOLD DATE              PROPERTY TYPE  \
0       PAST SALE     March-14-1991  Single Family Residential   
1     MLS Listing               NaN                Condo/Co-op   
2       PAST SALE  February-19-2010  Single Family Residential   
3       PAST SALE               NaN  Single Family Residential   
4       PAST SALE               NaN  Single Family Residential   
...           ...               ...                        ...   
7061  MLS Listing               NaN  Single Family Residential   
7062  MLS Listing               NaN  Single Family Residential   
7063  MLS Listing               NaN  Single Family Residential   
7064  MLS Listing               NaN  Single Family Residential   
7065    PAST SALE    August-27-2010                  Townhouse   

                        ADDRESS       CITY STATE OR PROVINCE  zipcode  \
0               4442 S 351st St     Auburn                WA    98001   
1     28700 34th Ave S Unit M-3     Auburn                WA    98001   
2               3414 S 283rd Ln     Auburn                WA    98001   
3               29382 58th Ct S     Auburn                WA    98001   
4               29391 58th Ct S     Auburn                WA    98001   
...                         ...        ...               ...      ...   
7061            301 NW 100th St    Seattle                WA    98177   
7062            55 Spring Dr NW  Shoreline                WA    98177   
7063           1229 NW 122nd St    Seattle                WA    98177   
7064          1295 NW Elford Dr    Seattle                WA    98177   
7065       10130 C Holman Rd NW    Seattle                WA    98177   

           PRICE  BEDS  BATHS  ...                            SOURCE  \
0       549950.0   3.0    2.0  ...  NWMLS as Distributed by MLS Grid   
1       455000.0   2.0    2.0  ...  NWMLS as Distributed by MLS Grid   
2       599000.0   3.0    2.5  ...  NWMLS as Distributed by MLS Grid   
3       819950.0   4.0    2.5  ...  NWMLS as Distributed by MLS Grid   
4       860675.0   5.0    3.5  ...  NWMLS as Distributed by MLS Grid   
...          ...   ...    ...  ...                               ...   
7061   1398000.0   4.0    3.5  ...  NWMLS as Distributed by MLS Grid   
7062   4500000.0   3.0    3.5  ...  NWMLS as Distributed by MLS Grid   
7063   2399000.0   4.0    3.5  ...  NWMLS as Distributed by MLS Grid   
7064  10950000.0   4.0    5.0  ...  NWMLS as Distributed by MLS Grid   
7065    575000.0   3.0    1.5  ...  NWMLS as Distributed by MLS Grid   

           MLS#  FAVORITE  INTERESTED   LATITUDE   LONGITUDE  num_school  \
0       2221171         N           Y  47.287207 -122.278138          11   
1       2195712         N           Y  47.344974 -122.289366          11   
2       2227709         N           Y  47.347788 -122.290089          11   
3       2203868         N           Y  47.326852 -122.261718          11   
4       2189261         N           Y  47.326852 -122.261718          11   
...         ...       ...         ...        ...         ...         ...   
7061  2186750.0         N           Y  47.701517 -122.360742           4   
7062  2170295.0         N           Y  47.739328 -122.374897           4   
7063  2170063.0         N           Y  47.718042 -122.373280           4   
7064  2152029.0         N           Y  47.730286 -122.371717           4   
7065  2192480.0         N           Y  47.702735 -122.359131           4   

     school_rating_mean Bayes_RatingSchool crime_percentage  
0              1.454545           1.996248            28.96  
1              1.454545           1.996248            28.96  
2              1.454545           1.996248            28.96  
3              1.454545           1.996248            28.96  
4              1.454545           1.996248            28.96  
...                 ...                ...              ...  
7061           3.750000           3.617964            24.76  
7062           3.750000           3.617964            24.76  
70

In [72]:
KC1 = KC.loc[(KC['SOLD DATE'].isna()) | (KC['SOLD DATE'] <= datetime(2020,1,1))]

KC2 = KC1.loc[KC1['SALE TYPE'] == 'PAST SALE']

KC3 = KC.drop(KC2.index) ## all sales less than 2020, 1 Jan are moved

#KC3.loc[KC3['SALE TYPE'] == 'PAST SALE']

KC3

SALE TYPE SOLD DATE              PROPERTY TYPE  \
1     MLS Listing       NaT                Condo/Co-op   
9     MLS Listing       NaT                    Parking   
10    MLS Listing       NaT  Single Family Residential   
11    MLS Listing       NaT  Single Family Residential   
12    MLS Listing       NaT  Single Family Residential   
...           ...       ...                        ...   
7060  MLS Listing       NaT  Single Family Residential   
7061  MLS Listing       NaT  Single Family Residential   
7062  MLS Listing       NaT  Single Family Residential   
7063  MLS Listing       NaT  Single Family Residential   
7064  MLS Listing       NaT  Single Family Residential   

                        ADDRESS       CITY STATE OR PROVINCE  zipcode  \
1     28700 34th Ave S Unit M-3     Auburn                WA    98001   
9             2131 E St NE #306     Auburn                WA    98001   
10             30160 65th Ave S     Auburn                WA    98001   
11             33614 57th Ave S     Auburn                WA    98001   
12             28431 50th Ave S     Auburn                WA    98001   
...                         ...        ...               ...      ...   
7060           12011 9th Ave NW    Seattle                WA    98177   
7061            301 NW 100th St    Seattle                WA    98177   
7062            55 Spring Dr NW  Shoreline                WA    98177   
7063           1229 NW 122nd St    Seattle                WA    98177   
7064          1295 NW Elford Dr    Seattle                WA    98177   

           PRICE  BEDS  BATHS  ...                            SOURCE  \
1       455000.0   2.0    2.0  ...  NWMLS as Distributed by MLS Grid   
9       295000.0   1.0    0.5  ...  NWMLS as Distributed by MLS Grid   
10      968000.0   4.0    3.0  ...  NWMLS as Distributed by MLS Grid   
11      824500.0   4.0    2.5  ...  NWMLS as Distributed by MLS Grid   
12      559950.0   3.0    2.0  ...  NWMLS as Distributed by MLS Grid   
...          ...   ...    ...  ...                               ...   
7060   1599500.0   3.0    2.5  ...  NWMLS as Distributed by MLS Grid   
7061   1398000.0   4.0    3.5  ...  NWMLS as Distributed by MLS Grid   
7062   4500000.0   3.0    3.5  ...  NWMLS as Distributed by MLS Grid   
7063   2399000.0   4.0    3.5  ...  NWMLS as Distributed by MLS Grid   
7064  10950000.0   4.0    5.0  ...  NWMLS as Distributed by MLS Grid   

           MLS#  FAVORITE  INTERESTED   LATITUDE   LONGITUDE  num_school  \
1       2195712         N           Y  47.344974 -122.289366          11   
9       2239271         N           Y  47.326128 -122.224359          11   
10      2237156         N           Y  47.332783 -122.254283          11   
11      2215058         N           Y  47.300267 -122.263528          11   
12      2238756         N           Y  47.346122 -122.271547          11   
...         ...       ...         ...        ...         ...         ...   
7060  2191353.0         N           Y  47.716566 -122.368816           4   
7061  2186750.0         N           Y  47.701517 -122.360742           4   
7062  2170295.0         N           Y  47.739328 -122.374897           4   
7063  2170063.0         N           Y  47.718042 -122.373280           4   
7064  2152029.0         N           Y  47.730286 -122.371717           4   

     school_rating_mean Bayes_RatingSchool crime_percentage  
1              1.454545           1.996248            28.96  
9              1.454545           1.996248            28.96  
10             1.454545           1.996248            28.96  
11             1.454545           1.996248            28.96  
12             1.454545           1.996248            28.96  
...                 ...                ...              ...  
7060           3.750000           3.617964            24.76  
7061           3.750000           3.617964            24.76  
7062           3.750000           3.617964            24.76  
7063           3.750000           3.

In [84]:
KC4 = KC3 

In [76]:
KC3.loc[(KC3['PROPERTY TYPE'] != 'Vacant Land') & (KC3['PROPERTY TYPE'] == 'Parking')]

KC3['PROPERTY TYPE'].unique()

array(['Condo/Co-op', 'Parking', 'Single Family Residential',
       'Vacant Land', 'Mobile/Manufactured Home',
       'Multi-Family (2-4 Unit)', 'Townhouse', 'Multi-Family (5+ Unit)',
       'Other', 'Ranch', 'Moorage', 'Unknown'], dtype=object)

In [83]:
len(KC3.loc[KC3['PROPERTY TYPE']=='Moorage']) + len(KC3.loc[KC3['PROPERTY TYPE'] == 'Parking']) + len(KC3.loc[KC3['PROPERTY TYPE'] == 'Vacant Land']) + len(KC3.loc[KC3['PROPERTY TYPE'] == 'Other']) + len(KC3.loc[KC3['PROPERTY TYPE'] == 'Ranch']) + len(KC3.loc[KC3['PROPERTY TYPE'] == 'Unknown'])

431

In [91]:
features = ['Moorage', 'Parking', 'Vacant Land', 'Other', 'Ranch', 'Unknown']

l=pd.DataFrame({})

for feature in features:
    l = KC4.loc[KC4['PROPERTY TYPE'] == feature]
    KC4 = KC4.drop(l.index)
    l.drop(l.index)
                

KC4
    

SALE TYPE SOLD DATE              PROPERTY TYPE  \
1     MLS Listing       NaT                Condo/Co-op   
10    MLS Listing       NaT  Single Family Residential   
11    MLS Listing       NaT  Single Family Residential   
12    MLS Listing       NaT  Single Family Residential   
13    MLS Listing       NaT  Single Family Residential   
...           ...       ...                        ...   
7060  MLS Listing       NaT  Single Family Residential   
7061  MLS Listing       NaT  Single Family Residential   
7062  MLS Listing       NaT  Single Family Residential   
7063  MLS Listing       NaT  Single Family Residential   
7064  MLS Listing       NaT  Single Family Residential   

                        ADDRESS         CITY STATE OR PROVINCE  zipcode  \
1     28700 34th Ave S Unit M-3       Auburn                WA    98001   
10             30160 65th Ave S       Auburn                WA    98001   
11             33614 57th Ave S       Auburn                WA    98001   
12             28431 50th Ave S       Auburn                WA    98001   
13              4419 S 330th Pl  Federal Way                WA    98001   
...                         ...          ...               ...      ...   
7060           12011 9th Ave NW      Seattle                WA    98177   
7061            301 NW 100th St      Seattle                WA    98177   
7062            55 Spring Dr NW    Shoreline                WA    98177   
7063           1229 NW 122nd St      Seattle                WA    98177   
7064          1295 NW Elford Dr      Seattle                WA    98177   

           PRICE  BEDS  BATHS  ...                            SOURCE  \
1       455000.0   2.0    2.0  ...  NWMLS as Distributed by MLS Grid   
10      968000.0   4.0    3.0  ...  NWMLS as Distributed by MLS Grid   
11      824500.0   4.0    2.5  ...  NWMLS as Distributed by MLS Grid   
12      559950.0   3.0    2.0  ...  NWMLS as Distributed by MLS Grid   
13      700000.0   4.0    2.0  ...  NWMLS as Distributed by MLS Grid   
...          ...   ...    ...  ...                               ...   
7060   1599500.0   3.0    2.5  ...  NWMLS as Distributed by MLS Grid   
7061   1398000.0   4.0    3.5  ...  NWMLS as Distributed by MLS Grid   
7062   4500000.0   3.0    3.5  ...  NWMLS as Distributed by MLS Grid   
7063   2399000.0   4.0    3.5  ...  NWMLS as Distributed by MLS Grid   
7064  10950000.0   4.0    5.0  ...  NWMLS as Distributed by MLS Grid   

           MLS#  FAVORITE  INTERESTED   LATITUDE   LONGITUDE  num_school  \
1       2195712         N           Y  47.344974 -122.289366          11   
10      2237156         N           Y  47.332783 -122.254283          11   
11      2215058         N           Y  47.300267 -122.263528          11   
12      2238756         N           Y  47.346122 -122.271547          11   
13      2236049         N           Y  47.305266 -122.277175          11   
...         ...       ...         ...        ...         ...         ...   
7060  2191353.0         N           Y  47.716566 -122.368816           4   
7061  2186750.0         N           Y  47.701517 -122.360742           4   
7062  2170295.0         N           Y  47.739328 -122.374897           4   
7063  2170063.0         N           Y  47.718042 -122.373280           4   
7064  2152029.0         N           Y  47.730286 -122.371717           4   

     school_rating_mean Bayes_RatingSchool crime_percentage  
1              1.454545           1.996248            28.96  
10             1.454545           1.996248            28.96  
11             1.454545           1.996248            28.96  
12             1.454545           1.996248            28.96  
13             1.454545           1.996248            28.96  
...                 ...                ...              ...  
7060           3.750000           3.617964            24.76  
7061           3.750000           3.617964            24.76  
7062           3.750000           3.617964            24.76  
7063        

In [95]:
KC4['PROPERTY TYPE'].unique()

array(['Condo/Co-op', 'Single Family Residential',
       'Mobile/Manufactured Home', 'Multi-Family (2-4 Unit)', 'Townhouse',
       'Multi-Family (5+ Unit)'], dtype=object)

In [96]:
KC4.loc[KC4['SALE TYPE'] == 'PAST SALE']

SALE TYPE  SOLD DATE              PROPERTY TYPE  \
36    PAST SALE 2020-09-01  Single Family Residential   
48    PAST SALE 2024-02-16  Single Family Residential   
50    PAST SALE 2024-03-13  Single Family Residential   
64    PAST SALE 2023-12-16  Single Family Residential   
69    PAST SALE 2024-02-01   Mobile/Manufactured Home   
...         ...        ...                        ...   
6978  PAST SALE 2022-03-15  Single Family Residential   
6984  PAST SALE 2020-11-06                Condo/Co-op   
7004  PAST SALE 2021-12-17   Mobile/Manufactured Home   
7021  PAST SALE 2024-01-11  Single Family Residential   
7041  PAST SALE 2023-07-12  Single Family Residential   

                           ADDRESS     CITY STATE OR PROVINCE  zipcode  \
36             35020 Military Rd S   Auburn                WA    98001   
48                 29708 32nd Pl S   Auburn                WA    98001   
50              1036 Algona Blvd N   Algona                WA    98001   
64                34914 45th Ave S   Auburn                WA    98001   
69                   118 2nd Ave S   Algona                WA    98001   
...                            ...      ...               ...      ...   
6978                150 S 132nd St   Burien                WA    98168   
6984  11009 Glen Acres Dr S Unit C  Seattle                WA    98168   
7004        12841 Occidental Ave S   Burien                WA    98168   
7021              10738 3rd Ave NW  Seattle                WA    98177   
7041              13528 3rd Ave NW  Seattle                WA    98177   

          PRICE  BEDS  BATHS  ...                            SOURCE  \
36     530000.0   3.0    2.0  ...  NWMLS as Distributed by MLS Grid   
48     585000.0   3.0    2.0  ...  NWMLS as Distributed by MLS Grid   
50     279900.0   4.0    2.0  ...  NWMLS as Distributed by MLS Grid   
64     570000.0   3.0    2.0  ...  NWMLS as Distributed by MLS Grid   
69     425000.0   3.0    2.0  ...  NWMLS as Distributed by MLS Grid   
...         ...   ...    ...  ...                               ...   
6978   779950.0   3.0    2.5  ...  NWMLS as Distributed by MLS Grid   
6984   355000.0   2.0    2.0  ...  NWMLS as Distributed by MLS Grid   
7004   379900.0   2.0    2.0  ...  NWMLS as Distributed by MLS Grid   
7021   924995.0   3.0    2.0  ...  NWMLS as Distributed by MLS Grid   
7041  1149950.0   3.0    3.5  ...  NWMLS as Distributed by MLS Grid   

           MLS#  FAVORITE  INTERESTED   LATITUDE   LONGITUDE  num_school  \
36      2232031         N           Y  47.287470 -122.270683          11   
48      2222534         N           Y  47.335586 -122.291225          11   
50      2195040         N           Y  47.291857 -122.254714          11   
64      2223893         N           Y  47.288015 -122.277326          11   
69      2210334         N           Y  47.277643 -122.254491          11   
...         ...       ...         ...        ...         ...         ...   
6978  2212845.0         N           Y  47.485117 -122.331550          13   
6984  2213069.0         N           Y  47.504895 -122.321061          13   
7004  2168053.0         N           Y  47.487259 -122.332866          13   
7021  2222527.0         N           Y  47.707934 -122.360478           4   
7041  2228621.0         N           Y  47.727613 -122.360680           4   

     school_rating_mean Bayes_RatingSchool crime_percentage  
36             1.454545           1.996248            28.96  
48             1.454545           1.996248            28.96  
50             1.454545           1.996248            28.96  
64             1.454545           1.996248            28.96  
69             1.454545           1.996248            28.96  
...                 ...                ...              ...  
6978           1.923077           2.290807            94.01  
6984           1.923077           2.290807            94.01  
7004           1.923077           2.290807            94.01  
7021           3.750000           3.617964    

In [9]:
KC.isna().sum()

SALE TYPE                                                                                         0
SOLD DATE                                                                                      5274
PROPERTY TYPE                                                                                     0
ADDRESS                                                                                          12
CITY                                                                                              2
STATE OR PROVINCE                                                                                 0
zipcode                                                                                           0
PRICE                                                                                             9
BEDS                                                                                            525
BATHS                                                                                           534


In [195]:
#drop the unnecessary columns
KC = KC.drop(columns=['SOLD DATE','ADDRESS','STATE OR PROVINCE', 'NEXT OPEN HOUSE START TIME',
       'NEXT OPEN HOUSE END TIME','HOA/MONTH', 'STATUS',
       'URL (SEE https://www.redfin.com/buy-a-home/comparative-market-analysis FOR INFO ON PRICING)',
       'SOURCE', 'MLS#', 'FAVORITE', 'INTERESTED', 'LATITUDE', 'LONGITUDE'])

In [196]:
KC

SALE TYPE              PROPERTY TYPE       CITY  zipcode       PRICE  \
0       PAST SALE  Single Family Residential     Auburn    98001    549950.0   
1     MLS Listing                Condo/Co-op     Auburn    98001    455000.0   
2       PAST SALE  Single Family Residential     Auburn    98001    599000.0   
3       PAST SALE  Single Family Residential     Auburn    98001    819950.0   
4       PAST SALE  Single Family Residential     Auburn    98001    860675.0   
...           ...                        ...        ...      ...         ...   
7061  MLS Listing  Single Family Residential    Seattle    98177   1398000.0   
7062  MLS Listing  Single Family Residential  Shoreline    98177   4500000.0   
7063  MLS Listing  Single Family Residential    Seattle    98177   2399000.0   
7064  MLS Listing  Single Family Residential    Seattle    98177  10950000.0   
7065    PAST SALE                  Townhouse    Seattle    98177    575000.0   

      BEDS  BATHS       LOCATION  SQUARE FEET  LOT SIZE  YEAR BUILT  \
0      3.0    2.0         Auburn       1340.0    9600.0      1964.0   
1      2.0    2.0         Auburn       1280.0       NaN      2003.0   
2      3.0    2.5      West Hill       1599.0       NaN      2003.0   
3      4.0    2.5      West Hill       2414.0    5872.0      2024.0   
4      5.0    3.5      West Hill       2853.0    6804.0      2023.0   
...    ...    ...            ...          ...       ...         ...   
7061   4.0    3.5     Crown Hill       2590.0    2925.0      2024.0   
7062   3.0    3.5  The Highlands       3410.0   98712.0      1986.0   
7063   4.0    3.5      Broadview       3330.0    7836.0      2022.0   
7064   4.0    5.0      Broadview       7362.0  108028.0      2001.0   
7065   3.0    1.5      Greenwood       1240.0    1090.0      2010.0   

      DAYS ON MARKET  $/SQUARE FEET  num_school  school_rating_mean  \
0               13.0          410.0          11            1.454545   
1               15.0          355.0          11            1.454545   
2               19.0          375.0          11            1.454545   
3                1.0          340.0          11            1.454545   
4              127.0          302.0          11            1.454545   
...              ...            ...         ...                 ...   
7061           147.0          540.0           4            3.750000   
7062           193.0         1320.0           4            3.750000   
7063           217.0          720.0           4            3.750000   
7064           271.0         1487.0           4            3.750000   
7065            67.0          464.0           4            3.750000   

      Bayes_RatingSchool  crime_percentage  
0               1.996248             28.96  
1               1.996248             28.96  
2               1.996248             28.96  
3               1.996248             28.96  
4               1.996248             28.96  
...                  ...               ...  
7061            3.617964             24.76  
7062            3.617964             24.76  
7063            3.617964             24.76  
7064            3.617964             24.76  
7065            3.617964             24.76  

[7066 rows x 17 columns]

### Look at the columns that have missing values

In [197]:
KC.isna().sum()

SALE TYPE                0
PROPERTY TYPE            0
CITY                     2
zipcode                  0
PRICE                    9
BEDS                   525
BATHS                  534
LOCATION                14
SQUARE FEET            525
LOT SIZE              1820
YEAR BUILT             696
DAYS ON MARKET           0
$/SQUARE FEET          525
num_school               0
school_rating_mean       0
Bayes_RatingSchool       0
crime_percentage         0
dtype: int64

Notice KC includes the rows for which property = land, for this type the columns beds, baths are obviously not availble. so lets filter out these rows. and then look at the missing values.



In [198]:
KC_not_land = KC[KC['PROPERTY TYPE']!='Vacant Land']
KC_not_land

SALE TYPE              PROPERTY TYPE       CITY  zipcode       PRICE  \
0       PAST SALE  Single Family Residential     Auburn    98001    549950.0   
1     MLS Listing                Condo/Co-op     Auburn    98001    455000.0   
2       PAST SALE  Single Family Residential     Auburn    98001    599000.0   
3       PAST SALE  Single Family Residential     Auburn    98001    819950.0   
4       PAST SALE  Single Family Residential     Auburn    98001    860675.0   
...           ...                        ...        ...      ...         ...   
7061  MLS Listing  Single Family Residential    Seattle    98177   1398000.0   
7062  MLS Listing  Single Family Residential  Shoreline    98177   4500000.0   
7063  MLS Listing  Single Family Residential    Seattle    98177   2399000.0   
7064  MLS Listing  Single Family Residential    Seattle    98177  10950000.0   
7065    PAST SALE                  Townhouse    Seattle    98177    575000.0   

      BEDS  BATHS       LOCATION  SQUARE FEET  LOT SIZE  YEAR BUILT  \
0      3.0    2.0         Auburn       1340.0    9600.0      1964.0   
1      2.0    2.0         Auburn       1280.0       NaN      2003.0   
2      3.0    2.5      West Hill       1599.0       NaN      2003.0   
3      4.0    2.5      West Hill       2414.0    5872.0      2024.0   
4      5.0    3.5      West Hill       2853.0    6804.0      2023.0   
...    ...    ...            ...          ...       ...         ...   
7061   4.0    3.5     Crown Hill       2590.0    2925.0      2024.0   
7062   3.0    3.5  The Highlands       3410.0   98712.0      1986.0   
7063   4.0    3.5      Broadview       3330.0    7836.0      2022.0   
7064   4.0    5.0      Broadview       7362.0  108028.0      2001.0   
7065   3.0    1.5      Greenwood       1240.0    1090.0      2010.0   

      DAYS ON MARKET  $/SQUARE FEET  num_school  school_rating_mean  \
0               13.0          410.0          11            1.454545   
1               15.0          355.0          11            1.454545   
2               19.0          375.0          11            1.454545   
3                1.0          340.0          11            1.454545   
4              127.0          302.0          11            1.454545   
...              ...            ...         ...                 ...   
7061           147.0          540.0           4            3.750000   
7062           193.0         1320.0           4            3.750000   
7063           217.0          720.0           4            3.750000   
7064           271.0         1487.0           4            3.750000   
7065            67.0          464.0           4            3.750000   

      Bayes_RatingSchool  crime_percentage  
0               1.996248             28.96  
1               1.996248             28.96  
2               1.996248             28.96  
3               1.996248             28.96  
4               1.996248             28.96  
...                  ...               ...  
7061            3.617964             24.76  
7062            3.617964             24.76  
7063            3.617964             24.76  
7064            3.617964             24.76  
7065            3.617964             24.76  

[6554 rows x 17 columns]

In [199]:
KC_not_land.isna().sum()

SALE TYPE                0
PROPERTY TYPE            0
CITY                     0
zipcode                  0
PRICE                    9
BEDS                    14
BATHS                   22
LOCATION                11
SQUARE FEET             13
LOT SIZE              1819
YEAR BUILT             184
DAYS ON MARKET           0
$/SQUARE FEET           13
num_school               0
school_rating_mean       0
Bayes_RatingSchool       0
crime_percentage         0
dtype: int64

* AMong the columns with missing values, the least important ones are location, $/square feet. we can drop these columns. Other columns are important features. So, we need to figure out how to replace these missing values or drop the rows?



* there are 11 rows for which locatio column is missing. Let's look at these rows.


In [200]:
rows_with_location_na = KC_not_land[KC_not_land['LOCATION'].isna()]
rows_with_location_na

SALE TYPE              PROPERTY TYPE          CITY  zipcode  \
445   MLS Listing  Single Family Residential   Hunts Point    98004   
520   MLS Listing  Single Family Residential      Bellevue    98004   
550   MLS Listing  Single Family Residential   Hunts Point    98004   
749   MLS Listing  Single Family Residential      Bellevue    98007   
2501  MLS Listing  Single Family Residential  Maple Valley    98038   
2879    PAST SALE  Single Family Residential       Redmond    98052   
3347  MLS Listing  Single Family Residential        Renton    98058   
4044  MLS Listing  Single Family Residential        Auburn    98092   
4615  MLS Listing  Single Family Residential       Seattle    98105   
5042  MLS Listing  Single Family Residential       Seattle    98112   
5083  MLS Listing  Single Family Residential       Seattle    98112   

           PRICE  BEDS  BATHS LOCATION  SQUARE FEET  LOT SIZE  YEAR BUILT  \
445   41000000.0   5.0    5.5      NaN       7750.0   48321.0      1989.0   
520   14500000.0   4.0    4.5      NaN       6290.0    8005.0      2001.0   
550   70000000.0   5.0    8.0      NaN      17599.0  187434.0      1995.0   
749    2399000.0  11.0    5.5      NaN       4820.0    7632.0      1962.0   
2501   1899000.0   4.0    3.5      NaN       4730.0  215186.0      1968.0   
2879   2250000.0  11.0    6.5      NaN       4620.0   12480.0      1973.0   
3347   1259950.0   8.0    2.5      NaN       2460.0   11275.0      1970.0   
4044   1749000.0   9.0    4.5      NaN       3880.0   10790.0      1968.0   
4615  23800000.0   6.0    8.5      NaN      11271.0   43068.0      1925.0   
5042  14900000.0   6.0    6.0      NaN       7910.0    9020.0      1924.0   
5083  19500000.0   3.0    4.5      NaN       6930.0   21406.0      2014.0   

      DAYS ON MARKET  $/SQUARE FEET  num_school  school_rating_mean  \
445              7.0         5290.0           4            4.500000   
520             72.0         2305.0           4            4.500000   
550            309.0         3977.0           4            4.500000   
749             35.0          498.0           5            2.600000   
2501            78.0          401.0           8            4.500000   
2879             1.0          487.0          17            4.941176   
3347             2.0          512.0          11            2.363636   
4044            35.0          451.0          13            2.846154   
4615            28.0         2112.0           3            4.666667   
5042             9.0         1884.0           4            4.000000   
5083           198.0         2814.0           4            4.000000   

      Bayes_RatingSchool  crime_percentage  
445             3.992964             74.23  
520             3.992964             74.23  
550             3.992964             74.23  
749             2.993746             26.44  
2501            4.161976             19.77  
2879            4.663986             39.11  
3347            2.662914             27.10  
4044            2.996689             23.99  
4615            3.991959             59.33  
5042            3.742964             36.46  
5083            3.742964             36.46

There are 11 rows for which location is missing. For these rows, other columns have values. SO, may be by looking at the zip code or city we may be able to figure out the location. 

Let's look at each city one by one. starting from Hunts Point. 

### Hunts Point.

In [201]:
KC_not_land[KC_not_land['CITY'] == 'Hunts Point']

SALE TYPE              PROPERTY TYPE         CITY  zipcode       PRICE  \
445  MLS Listing  Single Family Residential  Hunts Point    98004  41000000.0   
455  MLS Listing  Single Family Residential  Hunts Point    98004   9900000.0   
547  MLS Listing  Single Family Residential  Hunts Point    98004  23725000.0   
548  MLS Listing  Single Family Residential  Hunts Point    98004  34998000.0   
550  MLS Listing  Single Family Residential  Hunts Point    98004  70000000.0   

     BEDS  BATHS     LOCATION  SQUARE FEET  LOT SIZE  YEAR BUILT  \
445   5.0    5.5          NaN       7750.0   48321.0      1989.0   
455   5.0    3.5  Hunts Point       2440.0   40170.0      1918.0   
547   5.0    5.5  Hunts Point       5540.0   33452.0      1980.0   
548   5.0    3.5  Hunts Point       7140.0   80931.0      1947.0   
550   5.0    8.0          NaN      17599.0  187434.0      1995.0   

     DAYS ON MARKET  $/SQUARE FEET  num_school  school_rating_mean  \
445             7.0         5290.0           4                 4.5   
455             9.0         4057.0           4                 4.5   
547           260.0         4282.0           4                 4.5   
548           261.0         4902.0           4                 4.5   
550           309.0         3977.0           4                 4.5   

     Bayes_RatingSchool  crime_percentage  
445            3.992964             74.23  
455            3.992964             74.23  
547            3.992964             74.23  
548            3.992964             74.23  
550            3.992964             74.23

for 3 out of 5 the location for Hunts point for CITY = Hunts point is Hunts Point. So, we can replace Location value as Hunts Point. 

In [202]:
# Find rows where city is 'Hunts point' and location is NaN
condition = (KC_not_land['CITY'] == 'Hunts Point') & (KC_not_land['LOCATION'].isna())

# Replace NaN values in 'location' column with 'Hunts point' for those rows
KC_not_land.loc[condition, 'LOCATION'] = 'Hunts Point'

#check
KC_not_land[KC_not_land['CITY'] == 'Hunts Point']

SALE TYPE              PROPERTY TYPE         CITY  zipcode       PRICE  \
445  MLS Listing  Single Family Residential  Hunts Point    98004  41000000.0   
455  MLS Listing  Single Family Residential  Hunts Point    98004   9900000.0   
547  MLS Listing  Single Family Residential  Hunts Point    98004  23725000.0   
548  MLS Listing  Single Family Residential  Hunts Point    98004  34998000.0   
550  MLS Listing  Single Family Residential  Hunts Point    98004  70000000.0   

     BEDS  BATHS     LOCATION  SQUARE FEET  LOT SIZE  YEAR BUILT  \
445   5.0    5.5  Hunts Point       7750.0   48321.0      1989.0   
455   5.0    3.5  Hunts Point       2440.0   40170.0      1918.0   
547   5.0    5.5  Hunts Point       5540.0   33452.0      1980.0   
548   5.0    3.5  Hunts Point       7140.0   80931.0      1947.0   
550   5.0    8.0  Hunts Point      17599.0  187434.0      1995.0   

     DAYS ON MARKET  $/SQUARE FEET  num_school  school_rating_mean  \
445             7.0         5290.0           4                 4.5   
455             9.0         4057.0           4                 4.5   
547           260.0         4282.0           4                 4.5   
548           261.0         4902.0           4                 4.5   
550           309.0         3977.0           4                 4.5   

     Bayes_RatingSchool  crime_percentage  
445            3.992964             74.23  
455            3.992964             74.23  
547            3.992964             74.23  
548            3.992964             74.23  
550            3.992964             74.23

### Bellevue_98007

In [203]:
#Now check Bellevue	
KC_Bellevue = KC_not_land[KC_not_land['CITY'] == 'Bellevue']
KC_Bellevue

SALE TYPE              PROPERTY TYPE      CITY  zipcode      PRICE  \
380    PAST SALE                Condo/Co-op  Bellevue    98004  1697000.0   
381    PAST SALE                Condo/Co-op  Bellevue    98004  1119000.0   
382  MLS Listing                Condo/Co-op  Bellevue    98004   990000.0   
383  MLS Listing                  Townhouse  Bellevue    98004   625000.0   
384  MLS Listing                Condo/Co-op  Bellevue    98004   475000.0   
..           ...                        ...       ...      ...        ...   
815    PAST SALE  Single Family Residential  Bellevue    98008  4180000.0   
816    PAST SALE  Single Family Residential  Bellevue    98008  3148990.0   
817    PAST SALE  Single Family Residential  Bellevue    98008  2687000.0   
818    PAST SALE  Single Family Residential  Bellevue    98008  2000000.0   
819  MLS Listing  Single Family Residential  Bellevue    98008  3225000.0   

     BEDS  BATHS        LOCATION  SQUARE FEET  LOT SIZE  YEAR BUILT  \
380   2.0    2.0   West Bellevue       1681.0       NaN      1975.0   
381   1.0    1.5        Downtown       1352.0       NaN      2008.0   
382   3.0    2.5   West Bellevue       1704.0       NaN      1994.0   
383   2.0    1.5        Bellevue       1159.0       NaN      1980.0   
384   2.0    1.0        Downtown        835.0       NaN      1959.0   
..    ...    ...             ...          ...       ...         ...   
815   5.0    4.0  Lake Sammamish       4820.0   13208.0      2008.0   
816   6.0    5.5       Microsoft       4378.0    8715.0      2023.0   
817   5.0    4.5      Crossroads       4287.0    9440.0      2023.0   
818   6.0    4.0        Lochmoor       3910.0    9606.0      1968.0   
819   4.0    4.0  Lake Sammamish       4187.0   55162.0      2023.0   

     DAYS ON MARKET  $/SQUARE FEET  num_school  school_rating_mean  \
380             5.0         1010.0           4               4.500   
381            16.0          828.0           4               4.500   
382            49.0          581.0           4               4.500   
383            62.0          539.0           4               4.500   
384            99.0          569.0           4               4.500   
..              ...            ...         ...                 ...   
815            57.0          867.0           8               4.125   
816            70.0          719.0           8               4.125   
817           133.0          627.0           8               4.125   
818           202.0          512.0           8               4.125   
819           314.0          770.0           8               4.125   

     Bayes_RatingSchool  crime_percentage  
380            3.992964             74.23  
381            3.992964             74.23  
382            3.992964             74.23  
383            3.992964             74.23  
384            3.992964             74.23  
..                  ...               ...  
815            3.911976             28.51  
816            3.911976             28.51  
817            3.911976             28.51  
818            3.911976             28.51  
819            3.911976             28.51  

[396 rows x 17 columns]

The city Bellevue has lots of different locations. Let's narrow down using zip code = 98004 and find the highest occuring location. 


In [204]:
KC_Bellevue_98004 = KC_Bellevue[KC_Bellevue['zipcode'] == 98004]
KC_Bellevue_98004

SALE TYPE              PROPERTY TYPE      CITY  zipcode       PRICE  \
380    PAST SALE                Condo/Co-op  Bellevue    98004   1697000.0   
381    PAST SALE                Condo/Co-op  Bellevue    98004   1119000.0   
382  MLS Listing                Condo/Co-op  Bellevue    98004    990000.0   
383  MLS Listing                  Townhouse  Bellevue    98004    625000.0   
384  MLS Listing                Condo/Co-op  Bellevue    98004    475000.0   
..           ...                        ...       ...      ...         ...   
544  MLS Listing  Single Family Residential  Bellevue    98004   4495000.0   
545  MLS Listing                Condo/Co-op  Bellevue    98004    999000.0   
546  MLS Listing                Condo/Co-op  Bellevue    98004   1169000.0   
549  MLS Listing  Single Family Residential  Bellevue    98004  11875000.0   
551  MLS Listing  Single Family Residential  Bellevue    98004   2895000.0   

     BEDS  BATHS       LOCATION  SQUARE FEET  LOT SIZE  YEAR BUILT  \
380   2.0    2.0  West Bellevue       1681.0       NaN      1975.0   
381   1.0    1.5       Downtown       1352.0       NaN      2008.0   
382   3.0    2.5  West Bellevue       1704.0       NaN      1994.0   
383   2.0    1.5       Bellevue       1159.0       NaN      1980.0   
384   2.0    1.0       Downtown        835.0       NaN      1959.0   
..    ...    ...            ...          ...       ...         ...   
544   5.0    4.5    Meydenbauer       3850.0    9518.0      1976.0   
545   1.0    1.0       Downtown        570.0       NaN      2023.0   
546   2.0    2.0       Bellevue       1547.0       NaN      1994.0   
549   3.0    5.0         Enatai       5740.0   17396.0      1999.0   
551   5.0    4.0    Hunts Point       4290.0   31422.0      1979.0   

     DAYS ON MARKET  $/SQUARE FEET  num_school  school_rating_mean  \
380             5.0         1010.0           4                 4.5   
381            16.0          828.0           4                 4.5   
382            49.0          581.0           4                 4.5   
383            62.0          539.0           4                 4.5   
384            99.0          569.0           4                 4.5   
..              ...            ...         ...                 ...   
544           202.0         1168.0           4                 4.5   
545           210.0         1753.0           4                 4.5   
546           226.0          756.0           4                 4.5   
549           294.0         2069.0           4                 4.5   
551           393.0          675.0           4                 4.5   

     Bayes_RatingSchool  crime_percentage  
380            3.992964             74.23  
381            3.992964             74.23  
382            3.992964             74.23  
383            3.992964             74.23  
384            3.992964             74.23  
..                  ...               ...  
544            3.992964             74.23  
545            3.992964             74.23  
546            3.992964             74.23  
549            3.992964             74.23  
551            3.992964             74.23  

[139 rows x 17 columns]

In [205]:
KC_Bellevue_98004['LOCATION'].value_counts()

Downtown             76
West Bellevue        16
Bellevue             16
Enatai                9
Clyde Hill            7
Meydenbauer           6
Surrey Downs          3
Vuecrest              2
Downtown Bellevue     1
Beaux Arts            1
Hunts Point           1
Name: LOCATION, dtype: int64

Downtown  is the highest occuring location. So, replace location NaN values for the rows with city = Bellevue and zip code = 98004 with Downtown. 

In [206]:
# Find rows where city is 'Bellevue' and location is NaN and zip code = 98004
condition = (KC_not_land['CITY'] == 'Bellevue') & (KC_not_land['LOCATION'].isna()) & (KC_not_land['zipcode'] == 98004)

# Replace NaN values in 'location' column with 'Hunts point' for those rows
KC_not_land.loc[condition, 'LOCATION'] = 'Downtown'

#check
KC_not_land[KC_not_land['CITY'] == 'Bellevue']

SALE TYPE              PROPERTY TYPE      CITY  zipcode      PRICE  \
380    PAST SALE                Condo/Co-op  Bellevue    98004  1697000.0   
381    PAST SALE                Condo/Co-op  Bellevue    98004  1119000.0   
382  MLS Listing                Condo/Co-op  Bellevue    98004   990000.0   
383  MLS Listing                  Townhouse  Bellevue    98004   625000.0   
384  MLS Listing                Condo/Co-op  Bellevue    98004   475000.0   
..           ...                        ...       ...      ...        ...   
815    PAST SALE  Single Family Residential  Bellevue    98008  4180000.0   
816    PAST SALE  Single Family Residential  Bellevue    98008  3148990.0   
817    PAST SALE  Single Family Residential  Bellevue    98008  2687000.0   
818    PAST SALE  Single Family Residential  Bellevue    98008  2000000.0   
819  MLS Listing  Single Family Residential  Bellevue    98008  3225000.0   

     BEDS  BATHS        LOCATION  SQUARE FEET  LOT SIZE  YEAR BUILT  \
380   2.0    2.0   West Bellevue       1681.0       NaN      1975.0   
381   1.0    1.5        Downtown       1352.0       NaN      2008.0   
382   3.0    2.5   West Bellevue       1704.0       NaN      1994.0   
383   2.0    1.5        Bellevue       1159.0       NaN      1980.0   
384   2.0    1.0        Downtown        835.0       NaN      1959.0   
..    ...    ...             ...          ...       ...         ...   
815   5.0    4.0  Lake Sammamish       4820.0   13208.0      2008.0   
816   6.0    5.5       Microsoft       4378.0    8715.0      2023.0   
817   5.0    4.5      Crossroads       4287.0    9440.0      2023.0   
818   6.0    4.0        Lochmoor       3910.0    9606.0      1968.0   
819   4.0    4.0  Lake Sammamish       4187.0   55162.0      2023.0   

     DAYS ON MARKET  $/SQUARE FEET  num_school  school_rating_mean  \
380             5.0         1010.0           4               4.500   
381            16.0          828.0           4               4.500   
382            49.0          581.0           4               4.500   
383            62.0          539.0           4               4.500   
384            99.0          569.0           4               4.500   
..              ...            ...         ...                 ...   
815            57.0          867.0           8               4.125   
816            70.0          719.0           8               4.125   
817           133.0          627.0           8               4.125   
818           202.0          512.0           8               4.125   
819           314.0          770.0           8               4.125   

     Bayes_RatingSchool  crime_percentage  
380            3.992964             74.23  
381            3.992964             74.23  
382            3.992964             74.23  
383            3.992964             74.23  
384            3.992964             74.23  
..                  ...               ...  
815            3.911976             28.51  
816            3.911976             28.51  
817            3.911976             28.51  
818            3.911976             28.51  
819            3.911976             28.51  

[396 rows x 17 columns]

### Bellevue_98007

repeat the process for city = Bellevue and zip code = 98007	

In [207]:
KC_Bellevue_98007 = KC_Bellevue[KC_Bellevue['zipcode'] == 98007]
KC_Bellevue_98007

SALE TYPE              PROPERTY TYPE      CITY  zipcode      PRICE  \
713    PAST SALE                  Townhouse  Bellevue    98007   678000.0   
714  MLS Listing  Single Family Residential  Bellevue    98007  1199999.0   
715  MLS Listing                  Townhouse  Bellevue    98007   750000.0   
716  MLS Listing  Single Family Residential  Bellevue    98007  2290000.0   
717    PAST SALE                Condo/Co-op  Bellevue    98007   475000.0   
718  MLS Listing                Condo/Co-op  Bellevue    98007   559950.0   
719  MLS Listing  Single Family Residential  Bellevue    98007  1595000.0   
720    PAST SALE  Single Family Residential  Bellevue    98007  3150000.0   
721    PAST SALE                Condo/Co-op  Bellevue    98007   800000.0   
722    PAST SALE  Single Family Residential  Bellevue    98007  2098000.0   
723    PAST SALE                  Townhouse  Bellevue    98007   594900.0   
724    PAST SALE  Single Family Residential  Bellevue    98007  1794800.0   
725    PAST SALE                  Townhouse  Bellevue    98007  1050000.0   
726    PAST SALE  Single Family Residential  Bellevue    98007  1175000.0   
727    PAST SALE  Single Family Residential  Bellevue    98007  1875000.0   
728    PAST SALE                Condo/Co-op  Bellevue    98007   589000.0   
729    PAST SALE                Condo/Co-op  Bellevue    98007   339950.0   
730    PAST SALE  Single Family Residential  Bellevue    98007  1050000.0   
731    PAST SALE  Single Family Residential  Bellevue    98007  3499000.0   
732    PAST SALE  Single Family Residential  Bellevue    98007  1450000.0   
733    PAST SALE  Single Family Residential  Bellevue    98007  1625000.0   
734    PAST SALE                  Townhouse  Bellevue    98007   949000.0   
735  MLS Listing  Single Family Residential  Bellevue    98007  3498000.0   
736  MLS Listing                Condo/Co-op  Bellevue    98007   449000.0   
737  MLS Listing    Multi-Family (2-4 Unit)  Bellevue    98007  1595000.0   
738    PAST SALE                Condo/Co-op  Bellevue    98007   298000.0   
739  MLS Listing                Condo/Co-op  Bellevue    98007   259950.0   
740    PAST SALE                  Townhouse  Bellevue    98007  1250000.0   
741  MLS Listing  Single Family Residential  Bellevue    98007  2100000.0   
742  MLS Listing                Condo/Co-op  Bellevue    98007   459950.0   
743    PAST SALE  Single Family Residential  Bellevue    98007  1575000.0   
744    PAST SALE                Condo/Co-op  Bellevue    98007   529000.0   
745  MLS Listing                Condo/Co-op  Bellevue    98007   550000.0   
746  MLS Listing  Single Family Residential  Bellevue    98007  2598800.0   
747    PAST SALE                Condo/Co-op  Bellevue    98007   580000.0   
748  MLS Listing    Multi-Family (2-4 Unit)  Bellevue    98007  1975000.0   
749  MLS Listing  Single Family Residential  Bellevue    98007  2399000.0   
750  MLS Listing                Condo/Co-op  Bellevue    98007   325000.0   
751  MLS Listing                Condo/Co-op  Bellevue    98007   400000.0   
752  MLS Listing                Condo/Co-op  Bellevue    98007   629000.0   
753  MLS Listing  Single Family Residential  Bellevue    98007  3530000.0   
754  MLS Listing  Single Family Residential  Bellevue    98007  2200000.0   
755  MLS Listing  Single Family Residential  Bellevue    98007  1680000.0   
756  MLS Listing                Condo/Co-op  Bellevue    98007   385000.0   
757  MLS Listing                Condo/Co-op  Bellevue    98007   388000.0   
758  MLS Listing                Condo/Co-op  Bellevue    98007   389000.0   
760  MLS Listing                Condo/Co-op  Bellevue    98007   349999.0   

     BEDS  BATHS       LOCATION  SQUARE FEET  LOT SIZE  YEAR BUILT  \
713   2.0   2.50  Bridle Trails       1308.0       NaN      1979.0   
714   4.0   2.00     Lake Hills       2050.0    8400.0      1966.0   
715   3.0   2.50     Crossroads       1626.0  174514.0      1972.0   
716   4.0   3.50   College Hil

In [208]:
KC_Bellevue_98007['LOCATION'].value_counts()

Microsoft        11
Lake Hills        8
Bellevue          8
Robinswood        5
Bridle Trails     4
Crossroads        3
College Hill      2
Chevy Chase       2
Redmond           1
East Bellevue     1
Kelsey Creek      1
Name: LOCATION, dtype: int64

Microsoft is the highest occuring location. So, replace location NaN values for the rows with city = Bellevue and zip code = 98007 with Microsoft. 

In [209]:
# Find rows where city is 'Bellevue' and location is NaN and zip code = 98007
condition = (KC_not_land['CITY'] == 'Bellevue') & (KC_not_land['LOCATION'].isna()) & (KC_not_land['zipcode'] == 98007)

# Replace NaN values in 'location' column with 'Microsoft' for those rows
KC_not_land.loc[condition, 'LOCATION'] = 'Microsoft'

#check
KC_not_land[KC_not_land['CITY'] == 'Bellevue']

SALE TYPE              PROPERTY TYPE      CITY  zipcode      PRICE  \
380    PAST SALE                Condo/Co-op  Bellevue    98004  1697000.0   
381    PAST SALE                Condo/Co-op  Bellevue    98004  1119000.0   
382  MLS Listing                Condo/Co-op  Bellevue    98004   990000.0   
383  MLS Listing                  Townhouse  Bellevue    98004   625000.0   
384  MLS Listing                Condo/Co-op  Bellevue    98004   475000.0   
..           ...                        ...       ...      ...        ...   
815    PAST SALE  Single Family Residential  Bellevue    98008  4180000.0   
816    PAST SALE  Single Family Residential  Bellevue    98008  3148990.0   
817    PAST SALE  Single Family Residential  Bellevue    98008  2687000.0   
818    PAST SALE  Single Family Residential  Bellevue    98008  2000000.0   
819  MLS Listing  Single Family Residential  Bellevue    98008  3225000.0   

     BEDS  BATHS        LOCATION  SQUARE FEET  LOT SIZE  YEAR BUILT  \
380   2.0    2.0   West Bellevue       1681.0       NaN      1975.0   
381   1.0    1.5        Downtown       1352.0       NaN      2008.0   
382   3.0    2.5   West Bellevue       1704.0       NaN      1994.0   
383   2.0    1.5        Bellevue       1159.0       NaN      1980.0   
384   2.0    1.0        Downtown        835.0       NaN      1959.0   
..    ...    ...             ...          ...       ...         ...   
815   5.0    4.0  Lake Sammamish       4820.0   13208.0      2008.0   
816   6.0    5.5       Microsoft       4378.0    8715.0      2023.0   
817   5.0    4.5      Crossroads       4287.0    9440.0      2023.0   
818   6.0    4.0        Lochmoor       3910.0    9606.0      1968.0   
819   4.0    4.0  Lake Sammamish       4187.0   55162.0      2023.0   

     DAYS ON MARKET  $/SQUARE FEET  num_school  school_rating_mean  \
380             5.0         1010.0           4               4.500   
381            16.0          828.0           4               4.500   
382            49.0          581.0           4               4.500   
383            62.0          539.0           4               4.500   
384            99.0          569.0           4               4.500   
..              ...            ...         ...                 ...   
815            57.0          867.0           8               4.125   
816            70.0          719.0           8               4.125   
817           133.0          627.0           8               4.125   
818           202.0          512.0           8               4.125   
819           314.0          770.0           8               4.125   

     Bayes_RatingSchool  crime_percentage  
380            3.992964             74.23  
381            3.992964             74.23  
382            3.992964             74.23  
383            3.992964             74.23  
384            3.992964             74.23  
..                  ...               ...  
815            3.911976             28.51  
816            3.911976             28.51  
817            3.911976             28.51  
818            3.911976             28.51  
819            3.911976             28.51  

[396 rows x 17 columns]

### Maple Valley	98038	

In [210]:
Maple_Valley_98038 = KC_not_land[(KC_not_land['CITY'] == 'Maple Valley') & (KC_not_land['zipcode'] == 98038)]
Maple_Valley_98038

SALE TYPE              PROPERTY TYPE          CITY  zipcode  \
2402    PAST SALE  Single Family Residential  Maple Valley    98038   
2403  MLS Listing  Single Family Residential  Maple Valley    98038   
2404  MLS Listing  Single Family Residential  Maple Valley    98038   
2405  MLS Listing  Single Family Residential  Maple Valley    98038   
2406  MLS Listing  Single Family Residential  Maple Valley    98038   
...           ...                        ...           ...      ...   
2505    PAST SALE  Single Family Residential  Maple Valley    98038   
2506    PAST SALE  Single Family Residential  Maple Valley    98038   
2507    PAST SALE  Single Family Residential  Maple Valley    98038   
2508    PAST SALE  Single Family Residential  Maple Valley    98038   
2510    PAST SALE  Single Family Residential  Maple Valley    98038   

          PRICE  BEDS  BATHS         LOCATION  SQUARE FEET  LOT SIZE  \
2402  1515000.0   4.0    4.5     Maple Valley       4239.0    6605.0   
2403  2199950.0   4.0    5.0     Maple Valley       5370.0  218235.0   
2404   999950.0   5.0    3.0     Maple Valley       3080.0    4891.0   
2405   799000.0   3.0    2.0     Maple Valley       2710.0  445618.0   
2406   565000.0   3.0    2.0     Maple Valley       1800.0    5000.0   
...         ...   ...    ...              ...          ...       ...   
2505  1141950.0   4.0    2.5     Maple Valley       3115.0    5993.0   
2506  1398000.0   3.0    3.5  Lake Wilderness       2840.0    7118.0   
2507  1254900.0   4.0    4.0     Maple Valley       3858.0    5759.0   
2508  1183650.0   4.0    2.5     Maple Valley       3569.0    4940.0   
2510  1214450.0   4.0    3.5     Maple Valley       3858.0    6180.0   

      YEAR BUILT  DAYS ON MARKET  $/SQUARE FEET  num_school  \
2402      2024.0             2.0          357.0           8   
2403      2001.0            19.0          410.0           8   
2404      2021.0            90.0          325.0           8   
2405      1938.0             1.0          295.0           8   
2406      2005.0             1.0          314.0           8   
...          ...             ...            ...         ...   
2505      2023.0            93.0          367.0           8   
2506      2003.0            98.0          492.0           8   
2507      2023.0           117.0          325.0           8   
2508      2023.0           123.0          332.0           8   
2510      2023.0           143.0          315.0           8   

      school_rating_mean  Bayes_RatingSchool  crime_percentage  
2402                 4.5            4.161976             19.77  
2403                 4.5            4.161976             19.77  
2404                 4.5            4.161976             19.77  
2405                 4.5            4.161976             19.77  
2406                 4.5            4.161976             19.77  
...                  ...                 ...               ...  
2505                 4.5            4.161976             19.77  
2506                 4.5            4.161976             19.77  
2507                 4.5            4.161976             19.77  
2508                 4.5            4.161976             19.77  
2510                 4.5            4.161976             19.77  

[105 rows x 17 columns]

In [211]:
Maple_Valley_98038['LOCATION'].value_counts()

Maple Valley           61
Lake Wilderness        10
Hobart                  5
Four Corners            5
Highlands               4
Cherokee Bay            3
Cedar Downs             3
Elk Run Golf Course     3
Wilderness              2
Wilderness Village      1
Belmont Woods           1
East Maple Valley       1
Black Diamond           1
Katesridge              1
Covington               1
Lake Sawyer             1
Pla-mor                 1
Name: LOCATION, dtype: int64

Maple Valley is the highest occuring location. So, replace location NaN values for the rows with city = Maple Valley and zip code = 98038 with Maple Valley. 

In [212]:
# Find rows where city is 'Bellevue' and location is NaN and zip code = 98007
condition = (KC_not_land['CITY'] == 'Maple Valley') & (KC_not_land['LOCATION'].isna()) & (KC_not_land['zipcode'] == 98038)

# Replace NaN values in 'location' column with 'Microsoft' for those rows
KC_not_land.loc[condition, 'LOCATION'] = 'Maple Valley'

#check
KC_not_land[KC_not_land['CITY'] == 'Maple Valley']

SALE TYPE              PROPERTY TYPE          CITY  zipcode  \
820   MLS Listing  Single Family Residential  Maple Valley    98010   
2402    PAST SALE  Single Family Residential  Maple Valley    98038   
2403  MLS Listing  Single Family Residential  Maple Valley    98038   
2404  MLS Listing  Single Family Residential  Maple Valley    98038   
2405  MLS Listing  Single Family Residential  Maple Valley    98038   
...           ...                        ...           ...      ...   
2505    PAST SALE  Single Family Residential  Maple Valley    98038   
2506    PAST SALE  Single Family Residential  Maple Valley    98038   
2507    PAST SALE  Single Family Residential  Maple Valley    98038   
2508    PAST SALE  Single Family Residential  Maple Valley    98038   
2510    PAST SALE  Single Family Residential  Maple Valley    98038   

          PRICE  BEDS  BATHS         LOCATION  SQUARE FEET  LOT SIZE  \
820   1250000.0   5.0    3.0     Maple Valley       3510.0    5500.0   
2402  1515000.0   4.0    4.5     Maple Valley       4239.0    6605.0   
2403  2199950.0   4.0    5.0     Maple Valley       5370.0  218235.0   
2404   999950.0   5.0    3.0     Maple Valley       3080.0    4891.0   
2405   799000.0   3.0    2.0     Maple Valley       2710.0  445618.0   
...         ...   ...    ...              ...          ...       ...   
2505  1141950.0   4.0    2.5     Maple Valley       3115.0    5993.0   
2506  1398000.0   3.0    3.5  Lake Wilderness       2840.0    7118.0   
2507  1254900.0   4.0    4.0     Maple Valley       3858.0    5759.0   
2508  1183650.0   4.0    2.5     Maple Valley       3569.0    4940.0   
2510  1214450.0   4.0    3.5     Maple Valley       3858.0    6180.0   

      YEAR BUILT  DAYS ON MARKET  $/SQUARE FEET  num_school  \
820       2021.0             7.0          356.0           2   
2402      2024.0             2.0          357.0           8   
2403      2001.0            19.0          410.0           8   
2404      2021.0            90.0          325.0           8   
2405      1938.0             1.0          295.0           8   
...          ...             ...            ...         ...   
2505      2023.0            93.0          367.0           8   
2506      2003.0            98.0          492.0           8   
2507      2023.0           117.0          325.0           8   
2508      2023.0           123.0          332.0           8   
2510      2023.0           143.0          315.0           8   

      school_rating_mean  Bayes_RatingSchool  crime_percentage  
820                  3.5            3.490619             44.85  
2402                 4.5            4.161976             19.77  
2403                 4.5            4.161976             19.77  
2404                 4.5            4.161976             19.77  
2405                 4.5            4.161976             19.77  
...                  ...                 ...               ...  
2505                 4.5            4.161976             19.77  
2506                 4.5            4.161976             19.77  
2507                 4.5            4.161976             19.77  
2508                 4.5            4.161976             19.77  
2510                 4.5            4.161976             19.77  

[106 rows x 17 columns]

### Redmond	98052

In [213]:
Redmond_98052 = KC_not_land[(KC_not_land['CITY'] == 'Redmond') & (KC_not_land['zipcode'] == 98052)]
Redmond_98052

SALE TYPE              PROPERTY TYPE     CITY  zipcode  \
2867            MLS Listing                Condo/Co-op  Redmond    98052   
2868              PAST SALE  Single Family Residential  Redmond    98052   
2869              PAST SALE  Single Family Residential  Redmond    98052   
2870            MLS Listing                  Townhouse  Redmond    98052   
2871            MLS Listing                Condo/Co-op  Redmond    98052   
...                     ...                        ...      ...      ...   
3066  New Construction Plan                  Townhouse  Redmond    98052   
3067  New Construction Plan                Condo/Co-op  Redmond    98052   
3068              PAST SALE  Single Family Residential  Redmond    98052   
3069            MLS Listing                Condo/Co-op  Redmond    98052   
3070            MLS Listing   Mobile/Manufactured Home  Redmond    98052   

          PRICE  BEDS  BATHS          LOCATION  SQUARE FEET  LOT SIZE  \
2867   399000.0   1.0    1.0         Rose Hill        591.0       NaN   
2868  1349000.0   4.0    2.5    Education Hill       2120.0    8415.0   
2869  1999950.0   4.0    3.0   Grass Lawn Park       2950.0    7987.0   
2870  1295000.0   3.0    3.5           Redmond       2180.0    1763.0   
2871   575000.0   2.0    2.0    Education Hill        896.0       NaN   
...         ...   ...    ...               ...          ...       ...   
3066  1329990.0   3.0    3.5           Redmond       1769.0       NaN   
3067  1256995.0   2.0    2.0           Redmond       1259.0       NaN   
3068  1250000.0   3.0    1.5      Novelty Hill       2460.0   55321.0   
3069  1350000.0   3.0    3.5  Downtown Redmond       2335.0       NaN   
3070  5200000.0   2.0    1.5          Avondale       1056.0  608315.0   

      YEAR BUILT  DAYS ON MARKET  $/SQUARE FEET  num_school  \
2867      1985.0             1.0          675.0          17   
2868      1977.0             2.0          636.0          17   
2869      1966.0             3.0          678.0          17   
2870      2008.0            21.0          594.0          17   
2871      2001.0            35.0          642.0          17   
...          ...             ...            ...         ...   
3066         NaN             7.0          752.0          17   
3067         NaN            12.0          998.0          17   
3068      1942.0             6.0          508.0          17   
3069      2014.0            55.0          578.0          17   
3070      2009.0           105.0         4924.0          17   

      school_rating_mean  Bayes_RatingSchool  crime_percentage  
2867            4.941176            4.663986             39.11  
2868            4.941176            4.663986             39.11  
2869            4.941176            4.663986             39.11  
2870            4.941176            4.663986             39.11  
2871            4.941176            4.663986             39.11  
...                  ...                 ...               ...  
3066            4.941176            4.663986             39.11  
3067            4.941176            4.663986             39.11  
3068            4.941176            4.663986             39.11  
3069            4.941176            4.663986             39.11  
3070            4.941176            4.663986             39.11  

[198 rows x 17 columns]

In [214]:
Redmond_98052['LOCATION'].value_counts()

Union Hill             58
Education Hill         26
Redmond                24
Rose Hill              17
Downtown Redmond       13
Grass Lawn Park        11
Microsoft               9
West Lake Sammamish     7
English Hill            5
Totem Lake              5
North Rose Hill         5
Bridle Trails           4
Avondale                4
Marymoor                2
Idylwood                2
East Bellevue           1
Woodinville             1
Hollywood Hill          1
Lake Sammamish          1
Novelty Hill            1
Name: LOCATION, dtype: int64

Union Hill is the highest occuring location. So, replace location NaN values for the rows with city = Redmond and zip code = 98052 with Union Hill.

In [215]:
# Find rows where city is 'Redmond' and location is NaN and zip code = 98052
condition = (KC_not_land['CITY'] == 'Redmond') & (KC_not_land['LOCATION'].isna()) & (KC_not_land['zipcode'] == 98052)

# Replace NaN values in 'location' column with 'Union Hill' for those rows
KC_not_land.loc[condition, 'LOCATION'] = 'Union Hill'

#check
KC_not_land[KC_not_land['CITY'] == 'Redmond']

SALE TYPE              PROPERTY TYPE     CITY  zipcode      PRICE  \
2111    PAST SALE  Single Family Residential  Redmond    98033  3350000.0   
2867  MLS Listing                Condo/Co-op  Redmond    98052   399000.0   
2868    PAST SALE  Single Family Residential  Redmond    98052  1349000.0   
2869    PAST SALE  Single Family Residential  Redmond    98052  1999950.0   
2870  MLS Listing                  Townhouse  Redmond    98052  1295000.0   
...           ...                        ...      ...      ...        ...   
3122  MLS Listing   Mobile/Manufactured Home  Redmond    98053   850000.0   
3123  MLS Listing  Single Family Residential  Redmond    98053  1795000.0   
3124  MLS Listing  Single Family Residential  Redmond    98053  1800000.0   
3129  MLS Listing  Single Family Residential  Redmond    98053  2475000.0   
3131    PAST SALE  Single Family Residential  Redmond    98053  6950000.0   

      BEDS  BATHS         LOCATION  SQUARE FEET   LOT SIZE  YEAR BUILT  \
2111   5.0    4.5        Rose Hill       4235.0     9375.0      2024.0   
2867   1.0    1.0        Rose Hill        591.0        NaN      1985.0   
2868   4.0    2.5   Education Hill       2120.0     8415.0      1977.0   
2869   4.0    3.0  Grass Lawn Park       2950.0     7987.0      1966.0   
2870   3.0    3.5          Redmond       2180.0     1763.0      2008.0   
...    ...    ...              ...          ...        ...         ...   
3122   3.0    2.0       Union Hill       1900.0    44866.0      1990.0   
3123   4.0    3.0       Union Hill       4360.0    35042.0      2005.0   
3124   3.0    3.0       Union Hill       3140.0    51034.0      1982.0   
3129   5.0    3.5          Redmond       3600.0   167706.0      1957.0   
3131   5.0    5.0       Union Hill       4450.0  1556828.0      1956.0   

      DAYS ON MARKET  $/SQUARE FEET  num_school  school_rating_mean  \
2111             1.0          791.0          13            4.692308   
2867             1.0          675.0          17            4.941176   
2868             2.0          636.0          17            4.941176   
2869             3.0          678.0          17            4.941176   
2870            21.0          594.0          17            4.941176   
...              ...            ...         ...                 ...   
3122            58.0          447.0           8            4.875000   
3123            64.0          412.0           8            4.875000   
3124            66.0          573.0           8            4.875000   
3129           119.0          688.0           8            4.875000   
3131           574.0         1562.0           8            4.875000   

      Bayes_RatingSchool  crime_percentage  
2111            4.408454             30.27  
2867            4.663986             39.11  
2868            4.663986             39.11  
2869            4.663986             39.11  
2870            4.663986             39.11  
...                  ...               ...  
3122            4.411976             11.98  
3123            4.411976             11.98  
3124            4.411976             11.98  
3129            4.411976             11.98  
3131            4.411976             11.98  

[251 rows x 17 columns]

### Renton 98058

In [216]:
Renton_98058 = KC_not_land[(KC_not_land['CITY'] == 'Renton') & (KC_not_land['zipcode'] == 98058)]
Renton_98058

SALE TYPE              PROPERTY TYPE    CITY  zipcode  \
3324              PAST SALE  Single Family Residential  Renton    98058   
3325            MLS Listing  Single Family Residential  Renton    98058   
3326              PAST SALE                  Townhouse  Renton    98058   
3327              PAST SALE  Single Family Residential  Renton    98058   
3328            MLS Listing  Single Family Residential  Renton    98058   
...                     ...                        ...     ...      ...   
3429              PAST SALE                Condo/Co-op  Renton    98058   
3431  New Construction Home  Single Family Residential  Renton    98058   
3432  New Construction Home  Single Family Residential  Renton    98058   
3434              PAST SALE   Mobile/Manufactured Home  Renton    98058   
3435              PAST SALE  Single Family Residential  Renton    98058   

          PRICE  BEDS  BATHS     LOCATION  SQUARE FEET  LOT SIZE  YEAR BUILT  \
3324   799980.0   4.0    2.5     Fairwood       2010.0   12325.0      1984.0   
3325   649950.0   3.0    1.0       Renton       1490.0    7560.0      1958.0   
3326   489950.0   2.0    2.5       Renton       1149.0       NaN      2004.0   
3327   750000.0   5.0    2.5       Renton       2110.0    9025.0      1995.0   
3328   699950.0   4.0    3.0       Renton       2050.0    7245.0      1979.0   
...         ...   ...    ...          ...          ...       ...         ...   
3429   295000.0   2.0    1.0     Fairwood        787.0       NaN      1976.0   
3431  1198950.0   4.0    2.5       Renton       2556.0       NaN      2024.0   
3432  1374995.0   4.0    2.5       Renton       3402.0       NaN      2023.0   
3434   400000.0   3.0    2.0  Benson Hill       1520.0    7405.0      1978.0   
3435  1357700.0   4.0    4.0       Renton       3858.0    5985.0      2024.0   

      DAYS ON MARKET  $/SQUARE FEET  num_school  school_rating_mean  \
3324             1.0          398.0          11            2.363636   
3325             1.0          436.0          11            2.363636   
3326             4.0          426.0          11            2.363636   
3327            16.0          355.0          11            2.363636   
3328            27.0          341.0          11            2.363636   
...              ...            ...         ...                 ...   
3429           271.0          375.0          11            2.363636   
3431             7.0          469.0          11            2.363636   
3432            23.0          404.0          11            2.363636   
3434            11.0          263.0          11            2.363636   
3435            14.0          352.0          11            2.363636   

      Bayes_RatingSchool  crime_percentage  
3324            2.662914              27.1  
3325            2.662914              27.1  
3326            2.662914              27.1  
3327            2.662914              27.1  
3328            2.662914              27.1  
...                  ...               ...  
3429            2.662914              27.1  
3431            2.662914              27.1  
3432            2.662914              27.1  
3434            2.662914              27.1  
3435            2.662914              27.1  

[103 rows x 17 columns]

In [217]:
Renton_98058['LOCATION'].value_counts()

Renton                  31
Fairwood                27
Cascade                  6
Benson Hill              4
Maple Valley Heights     4
Cedar River              4
Spring Lake              3
Petrovitsky              3
Carriagewood             2
Summerfield              2
Maple Ridge              2
Tiffany Park             2
Maplewood                2
Rolling Hills            2
Fairwood Greens          2
East Renton              1
Spring Glen              1
Shadow Lake              1
Forest Estates           1
Lake Youngs              1
Lake Desire              1
Name: LOCATION, dtype: int64

Renton is the highest occuring location. So, replace location NaN values for the rows with city = Renton and zip code = 98058 with Renton.

In [218]:
# Find rows where city is 'Renton' and location is NaN and zip code = 98058
condition = (KC_not_land['CITY'] == 'Renton') & (KC_not_land['LOCATION'].isna()) & (KC_not_land['zipcode'] == 98058)

# Replace NaN values in 'location' column with 'Renton' for those rows
KC_not_land.loc[condition, 'LOCATION'] = 'Renton'

#check
KC_not_land[KC_not_land['CITY'] == 'Renton']

SALE TYPE              PROPERTY TYPE    CITY  zipcode  \
3132            MLS Listing  Single Family Residential  Renton    98055   
3133            MLS Listing  Single Family Residential  Renton    98055   
3134            MLS Listing                Condo/Co-op  Renton    98055   
3135            MLS Listing                Condo/Co-op  Renton    98055   
3136            MLS Listing                  Townhouse  Renton    98055   
...                     ...                        ...     ...      ...   
3531  New Construction Plan  Single Family Residential  Renton    98059   
3532  New Construction Plan  Single Family Residential  Renton    98059   
3533  New Construction Plan  Single Family Residential  Renton    98059   
3534  New Construction Plan  Single Family Residential  Renton    98059   
3535            MLS Listing                  Townhouse  Renton    98059   

          PRICE  BEDS  BATHS       LOCATION  SQUARE FEET  LOT SIZE  \
3132   875000.0   3.0    2.5    Talbot Hill       2740.0    8388.0   
3133   599950.0   3.0    2.0        Cascade       1120.0    9272.0   
3134   249900.0   1.0    1.0  Rolling Hills        696.0       NaN   
3135   299950.0   2.0    2.0  Rolling Hills        904.0       NaN   
3136   599995.0   3.0    2.5         Renton       1732.0       NaN   
...         ...   ...    ...            ...          ...       ...   
3531  1369995.0   6.0    2.5         Renton       2985.0       NaN   
3532  1489995.0   6.0    2.5         Renton       3259.0       NaN   
3533  1789995.0   6.0    2.5         Renton       3657.0       NaN   
3534  1299995.0   5.0    2.5         Renton       2770.0       NaN   
3535   475000.0   3.0    2.5      Highlands       1297.0       NaN   

      YEAR BUILT  DAYS ON MARKET  $/SQUARE FEET  num_school  \
3132      1987.0            42.0          319.0           5   
3133      1954.0             1.0          536.0           5   
3134      1978.0             1.0          359.0           5   
3135      1978.0             1.0          332.0           5   
3136      1997.0             1.0          346.0           5   
...          ...             ...            ...         ...   
3531         NaN            20.0          459.0          10   
3532         NaN            20.0          457.0          10   
3533         NaN            20.0          489.0          10   
3534         NaN            20.0          469.0          10   
3535      1980.0             7.0          366.0          10   

      school_rating_mean  Bayes_RatingSchool  crime_percentage  
3132                 3.8            3.660413             31.48  
3133                 3.8            3.660413             31.48  
3134                 3.8            3.660413             31.48  
3135                 3.8            3.660413             31.48  
3136                 3.8            3.660413             31.48  
...                  ...                 ...               ...  
3531                 4.1            3.924551             23.30  
3532                 4.1            3.924551             23.30  
3533                 4.1            3.924551             23.30  
3534                 4.1            3.924551             23.30  
3535                 4.1            3.924551             23.30  

[305 rows x 17 columns]

### Auburn	98092	

In [219]:
Auburn_98092 = KC_not_land[(KC_not_land['CITY'] == 'Auburn') & (KC_not_land['zipcode'] == 98092)]
Auburn_98092 

SALE TYPE              PROPERTY TYPE    CITY  zipcode      PRICE  \
3941  MLS Listing  Single Family Residential  Auburn    98092   835000.0   
3942  MLS Listing  Single Family Residential  Auburn    98092  1059000.0   
3943  MLS Listing                Condo/Co-op  Auburn    98092   410000.0   
3944    PAST SALE  Single Family Residential  Auburn    98092   649900.0   
3945    PAST SALE  Single Family Residential  Auburn    98092   575000.0   
...           ...                        ...     ...      ...        ...   
4080  MLS Listing  Single Family Residential  Auburn    98092  1385000.0   
4081  MLS Listing  Single Family Residential  Auburn    98092  1418000.0   
4082  MLS Listing  Single Family Residential  Auburn    98092  1300000.0   
4083  MLS Listing  Single Family Residential  Auburn    98092  1949995.0   
4086  MLS Listing  Single Family Residential  Auburn    98092  1199900.0   

      BEDS  BATHS             LOCATION  SQUARE FEET  LOT SIZE  YEAR BUILT  \
3941   3.0    2.0             Lea Hill       2780.0  211701.0      1959.0   
3942   5.0    3.0             Lakeland       3421.0   19607.0      2020.0   
3943   2.0    2.0             Lakeland       1007.0       NaN      2005.0   
3944   3.0    2.5             Lakeland       1710.0    9887.0      2010.0   
3945   3.0    2.5             Lakeland       1553.0    3200.0      2014.0   
...    ...    ...                  ...          ...       ...         ...   
4080   4.0    3.5             Lakeland       4100.0    9944.0      2024.0   
4081   4.0    3.0             Lakeland       3858.0   18004.0      2024.0   
4082   4.0    2.5             Lakeland       3093.0   19629.0      2024.0   
4083   4.0    2.5  Washington National       4200.0  946558.0      2001.0   
4086   4.0    3.0             Lea Hill       3436.0   15000.0      2023.0   

      DAYS ON MARKET  $/SQUARE FEET  num_school  school_rating_mean  \
3941             1.0          300.0          13            2.846154   
3942             1.0          310.0          13            2.846154   
3943             1.0          407.0          13            2.846154   
3944             5.0          380.0          13            2.846154   
3945             9.0          370.0          13            2.846154   
...              ...            ...         ...                 ...   
4080           242.0          338.0          13            2.846154   
4081           244.0          368.0          13            2.846154   
4082           244.0          420.0          13            2.846154   
4083           251.0          464.0          13            2.846154   
4086           355.0          349.0          13            2.846154   

      Bayes_RatingSchool  crime_percentage  
3941            2.996689             23.99  
3942            2.996689             23.99  
3943            2.996689             23.99  
3944            2.996689             23.99  
3945            2.996689             23.99  
...                  ...               ...  
4080            2.996689             23.99  
4081            2.996689             23.99  
4082            2.996689             23.99  
4083            2.996689             23.99  
4086            2.996689             23.99  

[136 rows x 17 columns]

In [220]:
Auburn_98092['LOCATION'].value_counts()

Lakeland               45
Lea Hill               29
Auburn                 23
Lake Holm               5
East Auburn             5
Green Valley            4
Green River College     3
Willow Park             3
Washington National     3
Kent                    2
Green River             2
East Hill               2
Lake Tapps              2
Janssen's               1
Dieringer               1
Forest Villa            1
Lake Morton             1
Cobble Creek            1
Lake Moneysmith         1
Wabash                  1
Name: LOCATION, dtype: int64

Lakeland is the highest occuring location. So, replace location NaN values for the rows with city = Auburn and zip code = 98092 with Renton.

In [221]:
# Find rows where city is 'Auburn' and location is NaN and zip code = 98092
condition = (KC_not_land['CITY'] == 'Auburn') & (KC_not_land['LOCATION'].isna()) & (KC_not_land['zipcode'] == 98092)

# Replace NaN values in 'location' column with 'Lakeland ' for those rows
KC_not_land.loc[condition, 'LOCATION'] = 'Lakeland'

#check
KC_not_land[KC_not_land['CITY'] == 'Auburn']

SALE TYPE              PROPERTY TYPE    CITY  zipcode      PRICE  \
0       PAST SALE  Single Family Residential  Auburn    98001   549950.0   
1     MLS Listing                Condo/Co-op  Auburn    98001   455000.0   
2       PAST SALE  Single Family Residential  Auburn    98001   599000.0   
3       PAST SALE  Single Family Residential  Auburn    98001   819950.0   
4       PAST SALE  Single Family Residential  Auburn    98001   860675.0   
...           ...                        ...     ...      ...        ...   
4080  MLS Listing  Single Family Residential  Auburn    98092  1385000.0   
4081  MLS Listing  Single Family Residential  Auburn    98092  1418000.0   
4082  MLS Listing  Single Family Residential  Auburn    98092  1300000.0   
4083  MLS Listing  Single Family Residential  Auburn    98092  1949995.0   
4086  MLS Listing  Single Family Residential  Auburn    98092  1199900.0   

      BEDS  BATHS             LOCATION  SQUARE FEET  LOT SIZE  YEAR BUILT  \
0      3.0    2.0               Auburn       1340.0    9600.0      1964.0   
1      2.0    2.0               Auburn       1280.0       NaN      2003.0   
2      3.0    2.5            West Hill       1599.0       NaN      2003.0   
3      4.0    2.5            West Hill       2414.0    5872.0      2024.0   
4      5.0    3.5            West Hill       2853.0    6804.0      2023.0   
...    ...    ...                  ...          ...       ...         ...   
4080   4.0    3.5             Lakeland       4100.0    9944.0      2024.0   
4081   4.0    3.0             Lakeland       3858.0   18004.0      2024.0   
4082   4.0    2.5             Lakeland       3093.0   19629.0      2024.0   
4083   4.0    2.5  Washington National       4200.0  946558.0      2001.0   
4086   4.0    3.0             Lea Hill       3436.0   15000.0      2023.0   

      DAYS ON MARKET  $/SQUARE FEET  num_school  school_rating_mean  \
0               13.0          410.0          11            1.454545   
1               15.0          355.0          11            1.454545   
2               19.0          375.0          11            1.454545   
3                1.0          340.0          11            1.454545   
4              127.0          302.0          11            1.454545   
...              ...            ...         ...                 ...   
4080           242.0          338.0          13            2.846154   
4081           244.0          368.0          13            2.846154   
4082           244.0          420.0          13            2.846154   
4083           251.0          464.0          13            2.846154   
4086           355.0          349.0          13            2.846154   

      Bayes_RatingSchool  crime_percentage  
0               1.996248             28.96  
1               1.996248             28.96  
2               1.996248             28.96  
3               1.996248             28.96  
4               1.996248             28.96  
...                  ...               ...  
4080            2.996689             23.99  
4081            2.996689             23.99  
4082            2.996689             23.99  
4083            2.996689             23.99  
4086            2.996689             23.99  

[312 rows x 17 columns]

### Seattle	98105	

In [222]:
Seattle_98105 = KC_not_land[(KC_not_land['CITY'] == 'Seattle') & (KC_not_land['zipcode'] == 98105)]
Seattle_98105 

SALE TYPE              PROPERTY TYPE     CITY  zipcode      PRICE  \
4552  MLS Listing                Condo/Co-op  Seattle    98105   369000.0   
4553    PAST SALE                Condo/Co-op  Seattle    98105   600000.0   
4554  MLS Listing  Single Family Residential  Seattle    98105  1199000.0   
4555    PAST SALE                  Townhouse  Seattle    98105   849950.0   
4556    PAST SALE                  Townhouse  Seattle    98105  1850000.0   
...           ...                        ...      ...      ...        ...   
4638    PAST SALE                Condo/Co-op  Seattle    98105   360000.0   
4639  MLS Listing                      Other  Seattle    98105   115000.0   
4640    PAST SALE     Multi-Family (5+ Unit)  Seattle    98105  2590000.0   
4641  MLS Listing                Condo/Co-op  Seattle    98105   555000.0   
4642  MLS Listing                Condo/Co-op  Seattle    98105   299000.0   

      BEDS  BATHS             LOCATION  SQUARE FEET  LOT SIZE  YEAR BUILT  \
4552   1.0    1.0               Bryant        605.0       NaN      1949.0   
4553   2.0    2.0  University District       1015.0       NaN      1996.0   
4554   4.0    2.0              Ravenna       2030.0    3697.0      1926.0   
4555   2.0    2.5          Wallingford       1200.0    1200.0      2024.0   
4556   5.0    3.5          Wallingford       2658.0    1200.0      2024.0   
...    ...    ...                  ...          ...       ...         ...   
4638   2.0    1.0          Laurelhurst       1191.0       NaN      1968.0   
4639   1.0    1.0  University District        142.0       1.0      1972.0   
4640   NaN    NaN  University District       5952.0    3878.0      1964.0   
4641   2.0    2.0  University District       1120.0   54280.0      1974.0   
4642   1.0    1.0  University District        670.0    9625.0      1926.0   

      DAYS ON MARKET  $/SQUARE FEET  num_school  school_rating_mean  \
4552             1.0          610.0           3            4.666667   
4553            13.0          591.0           3            4.666667   
4554            29.0          591.0           3            4.666667   
4555             1.0          708.0           3            4.666667   
4556            10.0          696.0           3            4.666667   
...              ...            ...         ...                 ...   
4638           100.0          302.0           3            4.666667   
4639           106.0          810.0           3            4.666667   
4640           151.0          435.0           3            4.666667   
4641           182.0          496.0           3            4.666667   
4642           244.0          446.0           3            4.666667   

      Bayes_RatingSchool  crime_percentage  
4552            3.991959             59.33  
4553            3.991959             59.33  
4554            3.991959             59.33  
4555            3.991959             59.33  
4556            3.991959             59.33  
...                  ...               ...  
4638            3.991959             59.33  
4639            3.991959             59.33  
4640            3.991959             59.33  
4641            3.991959             59.33  
4642            3.991959             59.33  

[90 rows x 17 columns]

In [223]:
Seattle_98105['LOCATION'].value_counts()

University District    35
Wallingford            17
Laurelhurst            11
Bryant                  6
Green Lake              5
Ravenna                 4
Hawthorne Hills         4
Roosevelt               2
Windermere              2
Sand Point              1
Belvedere Terrace       1
Seattle                 1
Name: LOCATION, dtype: int64

University District is the highest occuring location. So, replace location NaN values for the rows with city = Seattle and zip code = 98105 with University District.

In [224]:
# Find rows where city is 'Seattle' and location is NaN and zip code = 98105
condition = (KC_not_land['CITY'] == 'Seattle') & (KC_not_land['LOCATION'].isna()) & (KC_not_land['zipcode'] == 98105)

# Replace NaN values in 'location' column with 'University District ' for those rows
KC_not_land.loc[condition, 'LOCATION'] = 'University District'

#check
KC_not_land[KC_not_land['CITY'] == 'Seattle']

SALE TYPE              PROPERTY TYPE     CITY  zipcode       PRICE  \
4088  MLS Listing                Condo/Co-op  Seattle    98101    450000.0   
4089  MLS Listing                Condo/Co-op  Seattle    98101    699000.0   
4090  MLS Listing                Condo/Co-op  Seattle    98101    299000.0   
4091    PAST SALE                Condo/Co-op  Seattle    98101    825000.0   
4092  MLS Listing                Condo/Co-op  Seattle    98101    599000.0   
...           ...                        ...      ...      ...         ...   
7060  MLS Listing  Single Family Residential  Seattle    98177   1599500.0   
7061  MLS Listing  Single Family Residential  Seattle    98177   1398000.0   
7063  MLS Listing  Single Family Residential  Seattle    98177   2399000.0   
7064  MLS Listing  Single Family Residential  Seattle    98177  10950000.0   
7065    PAST SALE                  Townhouse  Seattle    98177    575000.0   

      BEDS  BATHS    LOCATION  SQUARE FEET  LOT SIZE  YEAR BUILT  \
4088   1.0    1.0  First Hill        621.0       NaN      2002.0   
4089   2.0    2.0     Seattle       1004.0       NaN      1991.0   
4090   0.0    1.0  First Hill        407.0       NaN      2001.0   
4091   1.0    1.0    Belltown        610.0       NaN      1991.0   
4092   1.0    1.0    Downtown        791.0       NaN      2020.0   
...    ...    ...         ...          ...       ...         ...   
7060   3.0    2.5   Broadview       2740.0    7531.0      2020.0   
7061   4.0    3.5  Crown Hill       2590.0    2925.0      2024.0   
7063   4.0    3.5   Broadview       3330.0    7836.0      2022.0   
7064   4.0    5.0   Broadview       7362.0  108028.0      2001.0   
7065   3.0    1.5   Greenwood       1240.0    1090.0      2010.0   

      DAYS ON MARKET  $/SQUARE FEET  num_school  school_rating_mean  \
4088             2.0          725.0           1                0.00   
4089             9.0          696.0           1                0.00   
4090            16.0          735.0           1                0.00   
4091            24.0         1352.0           1                0.00   
4092            29.0          757.0           1                0.00   
...              ...            ...         ...                 ...   
7060           120.0          584.0           4                3.75   
7061           147.0          540.0           4                3.75   
7063           217.0          720.0           4                3.75   
7064           271.0         1487.0           4                3.75   
7065            67.0          464.0           4                3.75   

      Bayes_RatingSchool  crime_percentage  
4088            2.788743            263.10  
4089            2.788743            263.10  
4090            2.788743            263.10  
4091            2.788743            263.10  
4092            2.788743            263.10  
...                  ...               ...  
7060            3.617964             24.76  
7061            3.617964             24.76  
7063            3.617964             24.76  
7064            3.617964             24.76  
7065            3.617964             24.76  

[2473 rows x 17 columns]

### Seattle	98112	

In [225]:
Seattle_98112 = KC_not_land[(KC_not_land['CITY'] == 'Seattle') & (KC_not_land['zipcode'] == 98112)]
Seattle_98112

SALE TYPE              PROPERTY TYPE     CITY  zipcode       PRICE  \
5002  MLS Listing                  Townhouse  Seattle    98112    895000.0   
5003  MLS Listing  Single Family Residential  Seattle    98112   1925000.0   
5004  MLS Listing  Single Family Residential  Seattle    98112   1375000.0   
5005  MLS Listing  Single Family Residential  Seattle    98112   1127500.0   
5006  MLS Listing  Single Family Residential  Seattle    98112   5989000.0   
...           ...                        ...      ...      ...         ...   
5083  MLS Listing  Single Family Residential  Seattle    98112  19500000.0   
5084  MLS Listing  Single Family Residential  Seattle    98112   5977000.0   
5085  MLS Listing  Single Family Residential  Seattle    98112   5500000.0   
5086  MLS Listing                Condo/Co-op  Seattle    98112   2988000.0   
5087  MLS Listing                Condo/Co-op  Seattle    98112    675000.0   

      BEDS  BATHS         LOCATION  SQUARE FEET  LOT SIZE  YEAR BUILT  \
5002   3.0    2.0          Seattle       1670.0     964.0      2001.0   
5003   2.0    2.0     Madison Park       2600.0    4000.0      1949.0   
5004   4.0    2.0         Montlake       1760.0    4416.0      1939.0   
5005   3.0    1.5     Capitol Hill       1880.0    3200.0      1903.0   
5006   5.0    5.5          Seattle       5330.0    7200.0      2024.0   
...    ...    ...              ...          ...       ...         ...   
5083   3.0    4.5              NaN       6930.0   21406.0      2014.0   
5084   5.0    6.5     Capitol Hill       9320.0   15660.0      1910.0   
5085   6.0    5.5  Washington Park       6228.0    7200.0      2001.0   
5086   3.0    4.0     Madison Park       3300.0       NaN      1969.0   
5087   2.0    1.0     Capitol Hill       1039.0       NaN      1928.0   

      DAYS ON MARKET  $/SQUARE FEET  num_school  school_rating_mean  \
5002            14.0          536.0           4                 4.0   
5003             1.0          740.0           4                 4.0   
5004             1.0          781.0           4                 4.0   
5005             1.0          600.0           4                 4.0   
5006             1.0         1124.0           4                 4.0   
...              ...            ...         ...                 ...   
5083           198.0         2814.0           4                 4.0   
5084           240.0          641.0           4                 4.0   
5085           315.0          883.0           4                 4.0   
5086           316.0          905.0           4                 4.0   
5087            63.0          650.0           4                 4.0   

      Bayes_RatingSchool  crime_percentage  
5002            3.742964             36.46  
5003            3.742964             36.46  
5004            3.742964             36.46  
5005            3.742964             36.46  
5006            3.742964             36.46  
...                  ...               ...  
5083            3.742964             36.46  
5084            3.742964             36.46  
5085            3.742964             36.46  
5086            3.742964             36.46  
5087            3.742964             36.46  

[83 rows x 17 columns]

In [226]:
Seattle_98112['LOCATION'].value_counts()

Madison Park          18
Capitol Hill          14
Madison Valley        13
North Capitol Hill     9
Washington Park        9
Montlake               8
Denny Blaine           4
Seattle                2
Broadmoor              2
Arboretum              1
Central Area           1
Name: LOCATION, dtype: int64

Madison Park is the highest occuring location. So, replace location NaN values for the rows with city = Seattle and zip code = 98112 with Madison Park.

In [227]:
# Find rows where city is 'Seattle' and location is NaN and zip code = 98112
condition = (KC_not_land['CITY'] == 'Seattle') & (KC_not_land['LOCATION'].isna()) & (KC_not_land['zipcode'] == 98112)

# Replace NaN values in 'location' column with 'Lakeland ' for those rows
KC_not_land.loc[condition, 'LOCATION'] = 'Madison Park'

#check
KC_not_land[KC_not_land['CITY'] == 'Seattle']

SALE TYPE              PROPERTY TYPE     CITY  zipcode       PRICE  \
4088  MLS Listing                Condo/Co-op  Seattle    98101    450000.0   
4089  MLS Listing                Condo/Co-op  Seattle    98101    699000.0   
4090  MLS Listing                Condo/Co-op  Seattle    98101    299000.0   
4091    PAST SALE                Condo/Co-op  Seattle    98101    825000.0   
4092  MLS Listing                Condo/Co-op  Seattle    98101    599000.0   
...           ...                        ...      ...      ...         ...   
7060  MLS Listing  Single Family Residential  Seattle    98177   1599500.0   
7061  MLS Listing  Single Family Residential  Seattle    98177   1398000.0   
7063  MLS Listing  Single Family Residential  Seattle    98177   2399000.0   
7064  MLS Listing  Single Family Residential  Seattle    98177  10950000.0   
7065    PAST SALE                  Townhouse  Seattle    98177    575000.0   

      BEDS  BATHS    LOCATION  SQUARE FEET  LOT SIZE  YEAR BUILT  \
4088   1.0    1.0  First Hill        621.0       NaN      2002.0   
4089   2.0    2.0     Seattle       1004.0       NaN      1991.0   
4090   0.0    1.0  First Hill        407.0       NaN      2001.0   
4091   1.0    1.0    Belltown        610.0       NaN      1991.0   
4092   1.0    1.0    Downtown        791.0       NaN      2020.0   
...    ...    ...         ...          ...       ...         ...   
7060   3.0    2.5   Broadview       2740.0    7531.0      2020.0   
7061   4.0    3.5  Crown Hill       2590.0    2925.0      2024.0   
7063   4.0    3.5   Broadview       3330.0    7836.0      2022.0   
7064   4.0    5.0   Broadview       7362.0  108028.0      2001.0   
7065   3.0    1.5   Greenwood       1240.0    1090.0      2010.0   

      DAYS ON MARKET  $/SQUARE FEET  num_school  school_rating_mean  \
4088             2.0          725.0           1                0.00   
4089             9.0          696.0           1                0.00   
4090            16.0          735.0           1                0.00   
4091            24.0         1352.0           1                0.00   
4092            29.0          757.0           1                0.00   
...              ...            ...         ...                 ...   
7060           120.0          584.0           4                3.75   
7061           147.0          540.0           4                3.75   
7063           217.0          720.0           4                3.75   
7064           271.0         1487.0           4                3.75   
7065            67.0          464.0           4                3.75   

      Bayes_RatingSchool  crime_percentage  
4088            2.788743            263.10  
4089            2.788743            263.10  
4090            2.788743            263.10  
4091            2.788743            263.10  
4092            2.788743            263.10  
...                  ...               ...  
7060            3.617964             24.76  
7061            3.617964             24.76  
7063            3.617964             24.76  
7064            3.617964             24.76  
7065            3.617964             24.76  

[2473 rows x 17 columns]

## Check if the location column is filled. 

In [228]:
KC_not_land.isna().sum()

SALE TYPE                0
PROPERTY TYPE            0
CITY                     0
zipcode                  0
PRICE                    9
BEDS                    14
BATHS                   22
LOCATION                 0
SQUARE FEET             13
LOT SIZE              1819
YEAR BUILT             184
DAYS ON MARKET           0
$/SQUARE FEET           13
num_school               0
school_rating_mean       0
Bayes_RatingSchool       0
crime_percentage         0
dtype: int64

## Location column is done. Let's look at property type further.

In [229]:
KC_not_land['PROPERTY TYPE'].value_counts()

Single Family Residential    3957
Condo/Co-op                  1485
Townhouse                     786
Mobile/Manufactured Home      149
Multi-Family (2-4 Unit)        80
Multi-Family (5+ Unit)         58
Other                          28
Moorage                         7
Ranch                           2
Parking                         1
Unknown                         1
Name: PROPERTY TYPE, dtype: int64

drop the rows for which property type = Other,Moorage,Ranch,Parking,Unknown  

In [230]:
# List of PROPERTY TYPE values to drop
types_to_drop = ['Other', 'Moorage', 'Ranch', 'Parking', 'Unknown']

# Drop rows where PROPERTY TYPE is in types_to_drop
KC_not_land = KC_not_land[~KC_not_land['PROPERTY TYPE'].isin(types_to_drop)]

# Display the cleaned DataFrame
KC_not_land


SALE TYPE              PROPERTY TYPE       CITY  zipcode       PRICE  \
0       PAST SALE  Single Family Residential     Auburn    98001    549950.0   
1     MLS Listing                Condo/Co-op     Auburn    98001    455000.0   
2       PAST SALE  Single Family Residential     Auburn    98001    599000.0   
3       PAST SALE  Single Family Residential     Auburn    98001    819950.0   
4       PAST SALE  Single Family Residential     Auburn    98001    860675.0   
...           ...                        ...        ...      ...         ...   
7061  MLS Listing  Single Family Residential    Seattle    98177   1398000.0   
7062  MLS Listing  Single Family Residential  Shoreline    98177   4500000.0   
7063  MLS Listing  Single Family Residential    Seattle    98177   2399000.0   
7064  MLS Listing  Single Family Residential    Seattle    98177  10950000.0   
7065    PAST SALE                  Townhouse    Seattle    98177    575000.0   

      BEDS  BATHS       LOCATION  SQUARE FEET  LOT SIZE  YEAR BUILT  \
0      3.0    2.0         Auburn       1340.0    9600.0      1964.0   
1      2.0    2.0         Auburn       1280.0       NaN      2003.0   
2      3.0    2.5      West Hill       1599.0       NaN      2003.0   
3      4.0    2.5      West Hill       2414.0    5872.0      2024.0   
4      5.0    3.5      West Hill       2853.0    6804.0      2023.0   
...    ...    ...            ...          ...       ...         ...   
7061   4.0    3.5     Crown Hill       2590.0    2925.0      2024.0   
7062   3.0    3.5  The Highlands       3410.0   98712.0      1986.0   
7063   4.0    3.5      Broadview       3330.0    7836.0      2022.0   
7064   4.0    5.0      Broadview       7362.0  108028.0      2001.0   
7065   3.0    1.5      Greenwood       1240.0    1090.0      2010.0   

      DAYS ON MARKET  $/SQUARE FEET  num_school  school_rating_mean  \
0               13.0          410.0          11            1.454545   
1               15.0          355.0          11            1.454545   
2               19.0          375.0          11            1.454545   
3                1.0          340.0          11            1.454545   
4              127.0          302.0          11            1.454545   
...              ...            ...         ...                 ...   
7061           147.0          540.0           4            3.750000   
7062           193.0         1320.0           4            3.750000   
7063           217.0          720.0           4            3.750000   
7064           271.0         1487.0           4            3.750000   
7065            67.0          464.0           4            3.750000   

      Bayes_RatingSchool  crime_percentage  
0               1.996248             28.96  
1               1.996248             28.96  
2               1.996248             28.96  
3               1.996248             28.96  
4               1.996248             28.96  
...                  ...               ...  
7061            3.617964             24.76  
7062            3.617964             24.76  
7063            3.617964             24.76  
7064            3.617964             24.76  
7065            3.617964             24.76  

[6515 rows x 17 columns]

In [231]:
KC_not_land['PROPERTY TYPE'].value_counts()

Single Family Residential    3957
Condo/Co-op                  1485
Townhouse                     786
Mobile/Manufactured Home      149
Multi-Family (2-4 Unit)        80
Multi-Family (5+ Unit)         58
Name: PROPERTY TYPE, dtype: int64

### LOT SIZE

In [232]:
rows_with_LOT_SIZE_na = KC_not_land[KC_not_land['LOT SIZE'].isna()]
rows_with_LOT_SIZE_na

SALE TYPE              PROPERTY TYPE       CITY  zipcode  \
1               MLS Listing                Condo/Co-op     Auburn    98001   
2                 PAST SALE  Single Family Residential     Auburn    98001   
141   New Construction Plan  Single Family Residential     Auburn    98001   
142   New Construction Plan  Single Family Residential     Auburn    98001   
143   New Construction Plan  Single Family Residential     Auburn    98001   
...                     ...                        ...        ...      ...   
6981            MLS Listing                Condo/Co-op    Seattle    98168   
6984              PAST SALE                Condo/Co-op    Seattle    98168   
6995            MLS Listing                Condo/Co-op    Seattle    98168   
6999            MLS Listing                Condo/Co-op    Seattle    98168   
7025              PAST SALE                Condo/Co-op  Shoreline    98177   

         PRICE  BEDS  BATHS        LOCATION  SQUARE FEET  LOT SIZE  \
1     455000.0   2.0    2.0          Auburn       1280.0       NaN   
2     599000.0   3.0    2.5       West Hill       1599.0       NaN   
141   809990.0   5.0    3.0          Auburn       2741.0       NaN   
142   779990.0   5.0    2.5          Auburn       2448.0       NaN   
143   769990.0   4.0    2.5          Auburn       2386.0       NaN   
...        ...   ...    ...             ...          ...       ...   
6981  289000.0   2.0    1.0  Boulevard Park        896.0       NaN   
6984  355000.0   2.0    2.0      Glen Acres       1302.0       NaN   
6995  375000.0   2.0    2.5      Glen Acres       1370.0       NaN   
6999  300000.0   2.0    2.0      Glen Acres       1400.0       NaN   
7025  399000.0   2.0    2.0  Richmond Beach       1079.0       NaN   

      YEAR BUILT  DAYS ON MARKET  $/SQUARE FEET  num_school  \
1         2003.0            15.0          355.0          11   
2         2003.0            19.0          375.0          11   
141          NaN            96.0          296.0          11   
142          NaN           100.0          319.0          11   
143          NaN           100.0          323.0          11   
...          ...             ...            ...         ...   
6981      1965.0            52.0          323.0          13   
6984      1979.0            55.0          273.0          13   
6995      1976.0            82.0          274.0          13   
6999      1967.0           105.0          214.0          13   
7025      1967.0             3.0          370.0           4   

      school_rating_mean  Bayes_RatingSchool  crime_percentage  
1               1.454545            1.996248             28.96  
2               1.454545            1.996248             28.96  
141             1.454545            1.996248             28.96  
142             1.454545            1.996248             28.96  
143             1.454545            1.996248             28.96  
...                  ...                 ...               ...  
6981            1.923077            2.290807             94.01  
6984            1.923077            2.290807             94.01  
6995            1.923077            2.290807             94.01  
6999            1.923077            2.290807             94.01  
7025            3.750000            3.617964             24.76  

[1812 rows x 17 columns]

Lot size is the size of the land on which the property is built plus the vacant land size.The price of property is definitly dependent on the lot size. Can we replace the n/a value swith the mean/median?

In [233]:
# look at the rows where 'PROPERTY TYPE'== 'Condo/Co-op'
KC_not_land[KC_not_land['PROPERTY TYPE'] == 'Condo/Co-op']

SALE TYPE PROPERTY TYPE         CITY  zipcode     PRICE  BEDS  BATHS  \
1     MLS Listing   Condo/Co-op       Auburn    98001  455000.0   2.0    2.0   
101     PAST SALE   Condo/Co-op       Auburn    98001  435000.0   2.0    2.5   
188   MLS Listing   Condo/Co-op       Auburn    98002  215000.0   1.0    1.0   
198     PAST SALE   Condo/Co-op       Auburn    98002  288000.0   2.0    2.0   
228     PAST SALE   Condo/Co-op  Federal Way    98003  249950.0   1.0    1.0   
...           ...           ...          ...      ...       ...   ...    ...   
6984    PAST SALE   Condo/Co-op      Seattle    98168  355000.0   2.0    2.0   
6995  MLS Listing   Condo/Co-op      Seattle    98168  375000.0   2.0    2.5   
6999  MLS Listing   Condo/Co-op      Seattle    98168  300000.0   2.0    2.0   
7025    PAST SALE   Condo/Co-op    Shoreline    98177  399000.0   2.0    2.0   
7049  MLS Listing   Condo/Co-op      Seattle    98177  789000.0   2.0    1.5   

            LOCATION  SQUARE FEET  LOT SIZE  YEAR BUILT  DAYS ON MARKET  \
1             Auburn       1280.0       NaN      2003.0            15.0   
101           Auburn       1360.0  223463.0      2003.0            46.0   
188           Auburn        609.0       NaN      1981.0            15.0   
198           Auburn        918.0  475240.0      1981.0            24.0   
228      Federal Way        623.0       NaN      1976.0             1.0   
...              ...          ...       ...         ...             ...   
6984      Glen Acres       1302.0       NaN      1979.0            55.0   
6995      Glen Acres       1370.0       NaN      1976.0            82.0   
6999      Glen Acres       1400.0       NaN      1967.0           105.0   
7025  Richmond Beach       1079.0       NaN      1967.0             3.0   
7049      Crown Hill       1100.0    2250.0      2024.0            15.0   

      $/SQUARE FEET  num_school  school_rating_mean  Bayes_RatingSchool  \
1             355.0          11            1.454545            1.996248   
101           320.0          11            1.454545            1.996248   
188           353.0          11            1.454545            1.996248   
198           314.0          11            1.454545            1.996248   
228           401.0          19            2.684211            2.823640   
...             ...         ...                 ...                 ...   
6984          273.0          13            1.923077            2.290807   
6995          274.0          13            1.923077            2.290807   
6999          214.0          13            1.923077            2.290807   
7025          370.0           4            3.750000            3.617964   
7049          717.0           4            3.750000            3.617964   

      crime_percentage  
1                28.96  
101              28.96  
188              47.16  
198              47.16  
228              51.17  
...                ...  
6984             94.01  
6995             94.01  
6999             94.01  
7025             24.76  
7049             24.76  

[1485 rows x 17 columns]

there are condos that have small square feet value but large lot size value. 

### what is lot size? is it the size of the land exclusing the building or the whole land including the building. find the rows where lot size is smaller than square feet.

In [234]:
condition = KC_not_land['SQUARE FEET'] > KC_not_land['LOT SIZE']
filtered_df = KC_not_land[condition]
filtered_df

SALE TYPE              PROPERTY TYPE      CITY  zipcode      PRICE  \
159     PAST SALE   Mobile/Manufactured Home    Auburn    98002    65000.0   
452   MLS Listing                  Townhouse  Bellevue    98004  2050000.0   
477   MLS Listing                  Townhouse  Bellevue    98004  2000000.0   
481   MLS Listing                  Townhouse  Bellevue    98004  1695000.0   
513   MLS Listing                  Townhouse  Bellevue    98004  2245000.0   
...           ...                        ...       ...      ...        ...   
6983  MLS Listing  Single Family Residential    Burien    98168   529950.0   
6987  MLS Listing  Single Family Residential    Burien    98168   529950.0   
6988  MLS Listing  Single Family Residential    Burien    98168   669950.0   
6998  MLS Listing                  Townhouse    Burien    98168   794950.0   
7065    PAST SALE                  Townhouse   Seattle    98177   575000.0   

      BEDS  BATHS   LOCATION  SQUARE FEET  LOT SIZE  YEAR BUILT  \
159    2.0    2.0     Auburn       1612.0       1.0      1979.0   
452    2.0    2.5   Downtown       2200.0    2062.0      2007.0   
477    4.0    3.0   Bellevue       2172.0       1.0      2010.0   
481    2.0    2.0   Downtown       1570.0    1108.0      2007.0   
513    3.0    3.5   Bellevue       2465.0    1461.0      2024.0   
...    ...    ...        ...          ...       ...         ...   
6983   2.0    1.5     Burien        800.0       1.0      2024.0   
6987   2.0    2.5     Burien        900.0       1.0      2024.0   
6988   3.0    2.5     Burien       1699.0       1.0      2024.0   
6998   4.0    3.5     Burien       2404.0    1857.0      2023.0   
7065   3.0    1.5  Greenwood       1240.0    1090.0      2010.0   

      DAYS ON MARKET  $/SQUARE FEET  num_school  school_rating_mean  \
159              3.0           40.0          11            1.454545   
452              9.0          932.0           4            4.500000   
477             21.0          921.0           4            4.500000   
481             28.0         1080.0           4            4.500000   
513             61.0          911.0           4            4.500000   
...              ...            ...         ...                 ...   
6983            54.0          662.0          13            1.923077   
6987            57.0          589.0          13            1.923077   
6988            57.0          394.0          13            1.923077   
6998           104.0          331.0          13            1.923077   
7065            67.0          464.0           4            3.750000   

      Bayes_RatingSchool  crime_percentage  
159             1.996248             47.16  
452             3.992964             74.23  
477             3.992964             74.23  
481             3.992964             74.23  
513             3.992964             74.23  
...                  ...               ...  
6983            2.290807             94.01  
6987            2.290807             94.01  
6988            2.290807             94.01  
6998            2.290807             94.01  
7065            3.617964             24.76  

[534 rows x 17 columns]

There are rows where lot size is smaller than square feet.that means lot size is not the land including building. But there are condos where lot size is larger than square feet?? 

### Drop rows where lot size = NaN

In [235]:
KC_not_land_cleaned = KC_not_land.dropna(subset=['LOT SIZE'])
KC_not_land_cleaned

SALE TYPE              PROPERTY TYPE       CITY  zipcode       PRICE  \
0       PAST SALE  Single Family Residential     Auburn    98001    549950.0   
3       PAST SALE  Single Family Residential     Auburn    98001    819950.0   
4       PAST SALE  Single Family Residential     Auburn    98001    860675.0   
5       PAST SALE  Single Family Residential     Auburn    98001    879950.0   
6       PAST SALE  Single Family Residential     Auburn    98001    782700.0   
...           ...                        ...        ...      ...         ...   
7061  MLS Listing  Single Family Residential    Seattle    98177   1398000.0   
7062  MLS Listing  Single Family Residential  Shoreline    98177   4500000.0   
7063  MLS Listing  Single Family Residential    Seattle    98177   2399000.0   
7064  MLS Listing  Single Family Residential    Seattle    98177  10950000.0   
7065    PAST SALE                  Townhouse    Seattle    98177    575000.0   

      BEDS  BATHS       LOCATION  SQUARE FEET  LOT SIZE  YEAR BUILT  \
0      3.0    2.0         Auburn       1340.0    9600.0      1964.0   
3      4.0    2.5      West Hill       2414.0    5872.0      2024.0   
4      5.0    3.5      West Hill       2853.0    6804.0      2023.0   
5      5.0    3.0      West Hill       2904.0    5446.0      2024.0   
6      4.0    2.5      West Hill       2039.0    4556.0      2024.0   
...    ...    ...            ...          ...       ...         ...   
7061   4.0    3.5     Crown Hill       2590.0    2925.0      2024.0   
7062   3.0    3.5  The Highlands       3410.0   98712.0      1986.0   
7063   4.0    3.5      Broadview       3330.0    7836.0      2022.0   
7064   4.0    5.0      Broadview       7362.0  108028.0      2001.0   
7065   3.0    1.5      Greenwood       1240.0    1090.0      2010.0   

      DAYS ON MARKET  $/SQUARE FEET  num_school  school_rating_mean  \
0               13.0          410.0          11            1.454545   
3                1.0          340.0          11            1.454545   
4              127.0          302.0          11            1.454545   
5                1.0          303.0          11            1.454545   
6                1.0          384.0          11            1.454545   
...              ...            ...         ...                 ...   
7061           147.0          540.0           4            3.750000   
7062           193.0         1320.0           4            3.750000   
7063           217.0          720.0           4            3.750000   
7064           271.0         1487.0           4            3.750000   
7065            67.0          464.0           4            3.750000   

      Bayes_RatingSchool  crime_percentage  
0               1.996248             28.96  
3               1.996248             28.96  
4               1.996248             28.96  
5               1.996248             28.96  
6               1.996248             28.96  
...                  ...               ...  
7061            3.617964             24.76  
7062            3.617964             24.76  
7063            3.617964             24.76  
7064            3.617964             24.76  
7065            3.617964             24.76  

[4703 rows x 17 columns]

In [239]:
KC_not_land_cleaned.isna().sum()

SALE TYPE             0
PROPERTY TYPE         0
CITY                  0
zipcode               0
PRICE                 0
BEDS                  2
BATHS                 2
LOCATION              0
SQUARE FEET           1
LOT SIZE              0
YEAR BUILT            0
DAYS ON MARKET        0
$/SQUARE FEET         1
num_school            0
school_rating_mean    0
Bayes_RatingSchool    0
crime_percentage      0
dtype: int64

## Dropping the rows with mssing LOT SIZE values also dropped most of rows for which other column values are also missing. now we have few missing values. Compared to the zise of the data set. this is only smalle percentage. so drop all rows with missing values. 

Only very few n/a values. Drop these also. 

In [242]:
KC_not_land_cleaned=KC_not_land_cleaned.dropna()

In [243]:
KC_not_land_cleaned

SALE TYPE              PROPERTY TYPE       CITY  zipcode       PRICE  \
0       PAST SALE  Single Family Residential     Auburn    98001    549950.0   
3       PAST SALE  Single Family Residential     Auburn    98001    819950.0   
4       PAST SALE  Single Family Residential     Auburn    98001    860675.0   
5       PAST SALE  Single Family Residential     Auburn    98001    879950.0   
6       PAST SALE  Single Family Residential     Auburn    98001    782700.0   
...           ...                        ...        ...      ...         ...   
7061  MLS Listing  Single Family Residential    Seattle    98177   1398000.0   
7062  MLS Listing  Single Family Residential  Shoreline    98177   4500000.0   
7063  MLS Listing  Single Family Residential    Seattle    98177   2399000.0   
7064  MLS Listing  Single Family Residential    Seattle    98177  10950000.0   
7065    PAST SALE                  Townhouse    Seattle    98177    575000.0   

      BEDS  BATHS       LOCATION  SQUARE FEET  LOT SIZE  YEAR BUILT  \
0      3.0    2.0         Auburn       1340.0    9600.0      1964.0   
3      4.0    2.5      West Hill       2414.0    5872.0      2024.0   
4      5.0    3.5      West Hill       2853.0    6804.0      2023.0   
5      5.0    3.0      West Hill       2904.0    5446.0      2024.0   
6      4.0    2.5      West Hill       2039.0    4556.0      2024.0   
...    ...    ...            ...          ...       ...         ...   
7061   4.0    3.5     Crown Hill       2590.0    2925.0      2024.0   
7062   3.0    3.5  The Highlands       3410.0   98712.0      1986.0   
7063   4.0    3.5      Broadview       3330.0    7836.0      2022.0   
7064   4.0    5.0      Broadview       7362.0  108028.0      2001.0   
7065   3.0    1.5      Greenwood       1240.0    1090.0      2010.0   

      DAYS ON MARKET  $/SQUARE FEET  num_school  school_rating_mean  \
0               13.0          410.0          11            1.454545   
3                1.0          340.0          11            1.454545   
4              127.0          302.0          11            1.454545   
5                1.0          303.0          11            1.454545   
6                1.0          384.0          11            1.454545   
...              ...            ...         ...                 ...   
7061           147.0          540.0           4            3.750000   
7062           193.0         1320.0           4            3.750000   
7063           217.0          720.0           4            3.750000   
7064           271.0         1487.0           4            3.750000   
7065            67.0          464.0           4            3.750000   

      Bayes_RatingSchool  crime_percentage  
0               1.996248             28.96  
3               1.996248             28.96  
4               1.996248             28.96  
5               1.996248             28.96  
6               1.996248             28.96  
...                  ...               ...  
7061            3.617964             24.76  
7062            3.617964             24.76  
7063            3.617964             24.76  
7064            3.617964             24.76  
7065            3.617964             24.76  

[4700 rows x 17 columns]

In [245]:
KC_not_land_cleaned.isna().sum()

SALE TYPE             0
PROPERTY TYPE         0
CITY                  0
zipcode               0
PRICE                 0
BEDS                  0
BATHS                 0
LOCATION              0
SQUARE FEET           0
LOT SIZE              0
YEAR BUILT            0
DAYS ON MARKET        0
$/SQUARE FEET         0
num_school            0
school_rating_mean    0
Bayes_RatingSchool    0
crime_percentage      0
dtype: int64

In [246]:
KC_not_land_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4700 entries, 0 to 7065
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   SALE TYPE           4700 non-null   object 
 1   PROPERTY TYPE       4700 non-null   object 
 2   CITY                4700 non-null   object 
 3   zipcode             4700 non-null   int64  
 4   PRICE               4700 non-null   float64
 5   BEDS                4700 non-null   float64
 6   BATHS               4700 non-null   float64
 7   LOCATION            4700 non-null   object 
 8   SQUARE FEET         4700 non-null   float64
 9   LOT SIZE            4700 non-null   float64
 10  YEAR BUILT          4700 non-null   float64
 11  DAYS ON MARKET      4700 non-null   float64
 12  $/SQUARE FEET       4700 non-null   float64
 13  num_school          4700 non-null   int64  
 14  school_rating_mean  4700 non-null   float64
 15  Bayes_RatingSchool  4700 non-null   float64
 16  crime_

# Save the cleaned to csv

In [247]:
KC_not_land_cleaned.to_csv(r'G:\My Drive\DS\Erdos\DS boot camp\Real Estate project\data gather\Cleaned_data.csv', index=False)